### ISSUE TITLE
DLC2 Install on MacOS. (error with intel-openmp distribution, and tips for wxPython)

### ISSUE THREAD

**Issue by jdabbi** [DeepLabCut/DeepLabCut#101]
Installing DeepLabCut on MacOS. Macbook to be specific.

I am getting the following error:

Could not find a version that satisfies the requirement intel-openmp (from deeplabcut) (from versions: )
No matching distribution found for intel-openmp (from deeplabcut)

Installed intel-openmp using conda. Upon reinstalling DLC, I still get the same error. 

Any pointers would be appreciated.

**Comment by jdabbi** [comment]
Here is a screen shot.
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/44908515/48285207-e0264380-e42f-11e8-8345-4f43638a9f8e.png">

**Comment by AlexEMG** [comment]
Dear @jdabbi ,

Unfortunately, I don't have experience with MacOS - would be great if someone else could chip in. 

Cheers,
Alexander

**Comment by MMathisLab** [comment]
(And right now we state in the install we only support Linux and Windows, sorry!)

**Comment by jdabbi** [comment]
Thank you for your help. Are there instructions on how to do this using AWS. I do not have access to a windows or linux machine

**Comment by AlexEMG** [comment]
There is one example here: https://github.com/AlexEMG/DeepLabCut/tree/master/examples for a notebook to run Google's Colaboratory Cloud -- this probably works similarly on AWS

**Comment by MMathisLab** [comment]
You can deploy a Docker container on AWS. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

We provide the Docker image here: https://github.com/MMathisLab/Docker4DeepLabCut2.0

However, you’ll have to label the images outside of Docker.... so you might have to either figure out how to install on MacOS, or try to use windows or Ubuntu. You likely can install this on your MacOS ... maybe this is useful: https://www.lifewire.com/dual-boot-linux-and-mac-os-4125733

**Comment by jdabbi** [comment]
Trying to use Google colabs and the Colab example. When I do a pip install of deeplabcut, I am getting the following message

google-colab 0.0.1a1 has requirement ipython~=5.5.0, but you'll have ipython 7.1.1 which is incompatible

Any suggestions would be appreciated

**Comment by MMathisLab** [comment]
Okay, I see an error I need to fix; but the ipython thing should be okay actually, it's more of a warning ;) I'll let you know when I fix it.

**Comment by MMathisLab** [comment]
are you clicking the link here?

![image](https://user-images.githubusercontent.com/28102185/48291609-19b57980-e445-11e8-89c7-0c52712a7572.png)

**Comment by MMathisLab** [comment]
Hi @jdabbi , I fixed an error in the Notebook, and we need to update pypi, but that should happen soon, so I'm posting this. 

If you click the blue Colab Here, things should work now:

![image](https://user-images.githubusercontent.com/28102185/48295652-0366e800-e45c-11e8-90f1-93e25c8de14e.png)

You should be able to run everything now... the ipython version warning is okay (you won't use ipython in the notebook). I also made a demo video for how to use this. I suggest "forking the repo," then you can save your edits, but also you can download it and place into your google drive. The Notebook will walk you through it, and here is a demo video: https://youtu.be/j13aXxysI2E

**Comment by MMathisLab** [comment]
Hi @jdabbi -  I went ahead and tried to install on my Macbook Pro... I did not use Anaconda, I did a direct install on my MacBook. (Using Anaconda is more difficult to get wxPython support...)

**MacOS Sierra - version 10.12.16**
Launch Terminal. 

``pip install --ignore-installed deeplabcut `` <--- I got no errors, and intel-openmp installed fine... (maybe try installing that package directly, as it works for me... https://pypi.org/project/intel-openmp/ , i.e. ``pip install intel-openmp``). 

To install wxPython you can use homebrew:
 http://macappstore.org/wxpython/
``ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null``
``brew install wxpython``
and/or: ``pip install wxpython``
You may have to troubleshoot wxPython a bit to get it to work, depending on how you installed python. 

then, ``pip install tensorflow=1.10``

But, DeepLabCut does install fine on my MacOS!

**Comment by MMathisLab** [comment]
Hi @jdabbi - I went ahead and tried to install on my Macbook Pro... I did not use Anaconda, I did a direct install on my MacBook. (Using Anaconda is more difficult to get wxPython support...*)

MacOS Sierra - version 10.12.16
Launch Terminal, then:

To install wxPython you can use homebrew: http://macappstore.org/wxpython/
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
``brew install wxpython``
and/or: ``pip install wxpython``
*NOTE: You may have to troubleshoot wxPython a bit to get it to work, depending on how you installed python, and especially if you are using Anaconda. See more here:
https://wiki.wxpython.org/wxPythonVirtualenvOnMac_

conda install python.app

then, ``pip install tensorflow==1.10``

``git clone https://github.com/AlexEMG/DeepLabCut``

go to this folder:
``cd DeepLabCut`` 

start python: 
``pythonw`` <--- *using **pythonw** I had  no issues with GUIS, i.e. wxPython! (see more here: https://docs.python.org/2/using/mac.html) 

``import deeplabcut`` (we are building directly from this git cloned folder then... but, I also tried pip install deeplabcut without issues...) I got no errors and intel-openmp installed fine...
![screen shot 2018-11-10 at 5 29 45 pm](https://user-images.githubusercontent.com/28102185/48307125-864b7980-e514-11e8-9599-064723e3a9a7.png)

However, the GUI wasn't designed for Mac, so the spacing is wide (this can be fixed); Maybe for now use an external monitor, as I couldn't see all the labels in my little macbook screen. I will keep this as a "to do" in the future, but at least for now, DeepLabCut **does work on MacOS** (although I will continue to advocate for users to use Ubuntu :).

**Comment by andydelgado0318** [comment]
AlexEMG I am using python 3.7

**Comment by andydelgado0318** [comment]
AlexEMG I am using Windows 10 64 bit as my OS

**Comment by MMathisLab** [comment]
Strange for Windows... but my experience seems it’s a permissions or complied/visual studio related error... can you open terminal as an admin and try again? (I’m also getting suspicious of python 3.7... I would use 3.6) ie even Tensorflow can be an issue with 3.7 https://www.reddit.com/r/tensorflow/comments/9eh1kf/i_have_python_37_installed_is_there_hope/

**Comment by MMathisLab** [comment]
Right click on “cmd” then “open as administrator”

**Comment by andydelgado0318** [comment]
I'm afraid I don't know what the cmd is

**Comment by andydelgado0318** [comment]
I've uninstalled 3.7 and am looking for 3.6, but my anaconda version also came with 3.7, am I going to have to install anaconda and reinstall it with 3.6?

**Comment by MMathisLab** [comment]
Please look at the linked biorxiv preprint which provides a full working protocol, and explains what cmd is. Also, on the Anaconda Homepage is has a link to previous versions of Anaconda with python 3.6.

**Comment by Bart-van-Alphen** [comment]
I'm getting the same error: 
"Could not find a version that satisfies the requirement intel-openmp (from deeplabcut) (from versions: )
No matching distribution found for intel-openmp (from deeplabcut)"

I'm using Windows 10, installed Python 3.6.7 (32-bit) and opened the terminal as Administrator to run 'pip install deeplabcut'

I tried installing older versions found at : https://pypi.org/project/intel-openmp/2019.0/  but they gave the same error...

**Comment by AlexEMG** [comment]
Dear Bart,

For windows we recommend using the Conda environment, that should take care of the openmp dependency  --- https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

________________________________

**Comment by Bart-van-Alphen** [comment]
Dear Alex,

Thank you for the quick reply. Using conda solved my problems!

**Comment by Laknath1996** [comment]
Hi, Is it possible to use Anaconda when installing deeplabcut? I created a conda virtual environment, installed the dependencies but however when I need to run the deeplabcut.label_frames(), the program crashes with the error '[wxNSApplication _setup:]: unrecognized selector sent to instance 0x7fbf83ce9e00' 
PS : This error occurs when I try to load the frames to the labelling window. 
Could this be due to a shortcoming of using conda?

**Comment by MMathisLab** [comment]
are you using MacOS? right now the GUIs are not supported in MacOS, but we are working on it; also instead of using python or ipython, you need to use pythonw - see the wiki above for some more tips on MacOS.

**Comment by Laknath1996** [comment]
Hi @MMathisLab, pardon me for not mentioning my specs in the previous post. I use MacOS Mojave version 10.14.2. I was using pythonw like you mentioned, but like I said previously, when I launched the labelling window using 'deeplabcut.label_frames()' and tried to load the frames for labelling, the window crashed with the error message  '[wxNSApplication _setup:]: unrecognized selector sent to instance 0x7fbf83ce9e00'. I did some searching about this error and found out that it could be solved by changing the backend of matplotlib from 'wxAgg' to 'tkAgg'. However, even after the change, the error still prevailed..

**Comment by Laknath1996** [comment]
Looking forward for the new release! :) Thanks, @MMathisLab

**Comment by alvarovegahd** [comment]
Hi, I had this same problem in a 32bit 16.04 ubuntu virtual machine. I figured that it was the 32bit distro. Using a 64bit distro fixed it; for some reason, the 32bit ubuntu distro does not seem to be supported.

**Comment by danbider** [comment]
Hello, 
Working with MacOS Mojave (version 10.14.2). 
I tried installing `deeplabcut` in two ways:

1. I created a conda virtual environment with python 3.6 and once in it, tried to ```pip install deeplabcut```. 
This raised the following error:
`ERROR: Exception:
Traceback (most recent call last):
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/download.py", line 928, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 735, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/anaconda3/envs/DLC/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 631, in unzip_file
    shutil.copyfileobj(fp, destfp)
  File "/anaconda3/envs/DLC/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/anaconda3/envs/DLC/lib/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/anaconda3/envs/DLC/lib/python3.6/zipfile.py", line 948, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set`

Didn't understand the error, and moved to:

2. Easy installation using the dlc-macOS-CPU.yaml file. The installation went smooth. Then I opened the terminal, and once inside the virtual environment, typed in `pythonw` followed by `import deeplabcut`. I was able to create a new project and copy videos to the folder. 

Then, when executing:
`deeplabcut.extract_frames(path_config_file, crop = True)`
the GUI opened up, i was able to mark the desired rectangle but then when I quit the GUI the terminal session was just stuck, as if still running. This was solved by 
`import matplotlib`
`matplotlib.use('Agg')`
That is, frames were extracted and saved in their cropped version the labeled-data folder.

Moving on to 
`deeplabcut.label_frames(path_config_file)`

The GUI opened, when I tried to select a folder of frames I wasn't able to do so, and got the following error:
`objc[47978]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9b47d210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x141e1ddc8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 428, in browseDir
    self.cfg = auxiliaryfunctions.read_config(self.config_file)
  File "/anaconda3/envs/dlc-macOS-CPU/lib/python3.6/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 125, in read_config
    raise FileNotFoundError ("Config file is not found. Please make sure that the file exists and/or there are no unnecessary spaces in the path of the config file!")
FileNotFoundError: Config file is not found. Please make sure that the file exists and/or there are no unnecessary spaces in the path of the config file!`

at other runs the GUI opened an image (can't reproduce what made it happen), yet I wasn't able to mark labels on the screen (using right clicks).

I validated that the config file was indeed in the right place with the right name, corresponding to the current working directory (also, otherwise it won't execute `extract_frames()`, right?).

Do you have any suggestions? looking forward to use the package for a fun neuroscience project, but it seems like something in my mac installation prevents me from doing so.

**Comment by AlexEMG** [comment]
See Forum: https://forum.image.sc/t/installation-on-mac-gui-issues/29198
