### ISSUE TITLE
refinement video GUI (for correcting individual frames post-DLC)

### ISSUE THREAD

**Issue by Jaclyneisdorfer** [DeepLabCut/DeepLabCut#1021]
Hello! 

We are using DLC for our injury model and it has worked phenomenally! However, at high levels of injury, we find that the injury causes abnormal gait, which in turns obstructs some features from the camera capture volume in several frames. DLC recognizes that the features are missing and produces a low likelihood for the x,y coordinates in the analysis csv file. Since the features are obstructed in those select frames, it does not matter how many training sessions we do, DLC will not be able to find the features because it can't see the features. Once the features are back in view, DLC is able to find and track the features with near perfect accuracy. What I would like to do is manually extract the obstructed features frames (like we do with the extract function), but instead of labeling and retraining, I'd like to manually correct the x,y coordinates in the analysis csv file. Is there a feature that can do this? 

Thank you!

**Comment by MMathisLab** [comment]
HI @Jaclyneisdorfer - glad to hear it's working well. There are two things possible; 1 is to actually train the network to guess - if you want to track obstructions, and you can guess, i.e. do the refinement, merge them in and re-train. Namely, when you label you can teach the network to guess; another is to of course as you suggest, "externally" manually correct frames as you want. 

We have a tracklet GUI for maDLC that allows this, but could be repurposed for this task if you want to hack it (or the refinement GUI for that matter). We don't have time right now (and it's a bit beyond the scope of DLC since what we want to give you is the best pose estimation tools, but leave post-processing elsewhere :)

Hope that helps!
