### ISSUE TITLE
Can DeepLabCut work for MacOS

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1046]
I am looking to buy a new laptop and would prefer to get a Macbook Pro, however I am concerned that I will not be able to run DeepLabCut effectively on it. Currently I use DeepLabCut on my Windows 10 laptop to label videos before I upload my projects to the cloud-based COLAB where they can be processed and analyzed.

What computer specs are necessary to run DeepLabCut effectively? Would DeepLabCut be compatible with the Apple M1 chip, since I've been using Intel i7 on my current Windows 10? My current labtop has 12 GB of RAM and 256 GB of storage, and my new Macbook would have at least that much as well.

**Comment by backyardbiomech** [comment]
Hi, @Hydraulic343: Many users I know, myself included, successfully run Deeplabcut on Intel MacBook Pros. The M1 chip is a big question, though. My wife recently purchased one, so I'm hoping to use some of my holiday "break" to test deeplabcut on that since I haven't seen anyone else bring it up.

I'm sure the developers would also appreciate this kind of question being posted on the image.sc forum instead of as an issue on GitHub, so when I get test results I'll post my findings over there.

**Comment by backyardbiomech** [comment]
I just ran a clean install on the M1 MacBook Pro, Big Sur, (macOS 11.1).

ffmpeg required a separate install (`condo install ffmpeg`)

I timed `testscript.py`:
`time pythonw testscript.py  565.57s user 186.21s system 274% cpu 4:33.95 total`
 It ran without a hitch. I then opened the test project in the GUI, and labeled frames, to make sure all the different GUIs worked. Other than having to drag to resize the main GUI to see all the buttons, everything I tested worked flawlessly.

**Comment by arge-7** [comment]
Other than the ffmpeg issue, did you just install it via `conda env create -f DLC-CPU.yaml` ?
I'm trying to run in on a new M1 Mac as well, but running into this issue:

`ResolvePackageNotFound: 
  - python=3.7
  - shapely
  - tensorflow==1.13.1`

**Comment by Joilence** [comment]
On my MacBook Air M1 2020 16G, macOS 11.2.3, conda 4.9.2, create the environment by `conda env create -f DLC-CPU.yaml`. The kernel would die every time when I "import deeplabcut" in Jupyter Notebook. `iPython` works fine so far though.

**Comment by MMathisLab** [comment]
@Joilence you should use `pythonw` -- see notes here: https://github.com/DeepLabCut/DeepLabCut/blob/821d3d9b10713963fc25b0e363fe93e3d3a29de3/docs/UseOverviewGuide.md#option-1-demo-notebooks

Option 1: Demo Notebooks:
🎥 VIDEO TUTORIAL AVAILABLE!

We provide Jupyter and COLAB notebooks for using DeepLabCut on both a pre-labeled dataset, and on the end user’s own dataset. See all the demo's here! Please note that GUIs are not easily supported in Jupyter in MacOS, as you need a framework build of python. While it's possible to launch them with a few tweaks, we recommend using the Project Manager GUI or terminal, so please follow the instructions below.

Option 2: using the Project Manager GUI:
🎥 VIDEO TUTORIAL! 🎥 VIDEO TUTORIAL#2!

Start iPython, or if you are using MacOS, you must use pythonw vs. typing ipython or python, but otherwise it's the same. If you are using DeepLabCut on the cloud, you cannot use the GUIs and you need to first set DLClight=True. If you use Windows, please always open the terminal with administrator privileges. Please read more here, and in our Nature Protocols paper here. And, see our troubleshooting wiki.

**Comment by Joilence** [comment]
@MMathisLab Thanks for the reply. I do not plan to use the GUI and am aware that on macOS `pythonw` is required for GUI. 

The current problem is a simple `import deeplabcut` would cause the Jupyter kernel die. Just put the information here and see if anyone else also have the same issue. Will update if I have something new.

<img width="1161" alt="CleanShot 2021-04-09 at 15 38 36@2x" src="https://user-images.githubusercontent.com/14588641/114188754-bdbeea00-9949-11eb-8f48-e716fc97f3f6.png">

```
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.7.1            py37hecd8cb5_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
ipython                   7.22.0           py37h01d92e1_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
```

**Comment by MMathisLab** [comment]
yesh, you need to edit jupyter for using jupyter due to the wxPythong binding. If you will use NO GUIs, then you should install and `import deeplabcutcore`

"Please note that GUIs are not easily supported in Jupyter in MacOS, as you need a framework build of python. While it's possible to launch them with a few tweaks, we recommend using the Project Manager GUI or terminal, so please follow the instructions below."

^^ that is why I suggest just using the terminal vs. jupyter

**Comment by arge-7** [comment]
> @MMathisLab Thanks for the reply. I do not plan to use the GUI and am aware that on macOS `pythonw` is required for GUI. 
> 
> 
> 
> The current problem is a simple `import deeplabcut` would cause the Jupyter kernel die. Just put the information here and see if anyone else also have the same issue. Will update if I have something new.
> 
> 
> 
> <img width="1161" alt="CleanShot 2021-04-09 at 15 38 36@2x" src="https://user-images.githubusercontent.com/14588641/114188754-bdbeea00-9949-11eb-8f48-e716fc97f3f6.png">
> 
> 
> 
> ```
> 
> jupyter                   1.0.0                    py37_7
> 
> jupyter_client            6.1.12             pyhd3eb1b0_0
> 
> jupyter_console           6.4.0              pyhd3eb1b0_0
> 
> jupyter_core              4.7.1            py37hecd8cb5_0
> 
> jupyterlab_pygments       0.1.2                      py_0
> 
> jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
> 
> ipython                   7.22.0           py37h01d92e1_0
> 
> ipython_genutils          0.2.0              pyhd3eb1b0_1
> 
> ```
> 
> 

Can you run the import command in terminal instead of Jupyter? Ive had problems with Jupyter using a different kernel than I thought it was which has led to lots of annoying errors in the past.

**Comment by Joilence** [comment]
> Can you run the import command in terminal instead of Jupyter?

@arge-7 Yes, it works fine for me both in `pythonw` (and launch GUI) and `iPython`.

---

@MMathisLab Thanks. I didn't realize there is `deeplabcutcore` existed and was trying to use `os.environ["DLClight"]="True"` as [the demo for Colab](https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/COLAB_DEMO_mouse_openfield.ipynb) did.

According to [DeepLabCut-core](https://github.com/DeepLabCut/DeepLabCut-core):

> UPDATE: We will be using this space as the tensorflow 2 test-bed, but then all DeepLabCut will be within the main package. The headless version will be `pip install deeplabcut`, while the full GUI supported version is `pip install deeplabcut[gui]`.

Does this mean I will be using `deeplabcut` in the future as I use `deeplabcutcore` now? And the current `deeplabcut` is still the full GUI supported version, right?

**Comment by Benthealchemist** [comment]
Hi, has anyone come up against the problem of 
**"zsh: illegal hardware instruction"**? upon importing DeepLabCut when using the M1 processor?


This seems to be attributed to tensor flow, I know there have been issues in the roll out of tf for M1 but in this thread it looks like people have overcome this, at least for running in pythonw or ipython.

Using tf v1.15, all deeplabcut modules installed from Conda. Have tried own pip install too but get the same issue.

Any help appreciated!

**Comment by arge-7** [comment]
@Benthealchemist I spent an ungodly amount of time trying to get it working on my M1 Mac, because it's my best option without having access to an Nvidia GPU workstation. You can only run M1-optimized Tensorflow via TF2, which is only supported by DeepLabCut-core. It's been a while since I tried, but I ran into dependency issues I couldn't solve. The big problem was Intel OpenMP which apparently doesn't run on M1 architecture. I'm a noob at all this and I've been learning as I go, but this was my experience.

**Comment by backyardbiomech** [comment]
Just to be clear, installing the DLC-CPU env works fine on every Mac I’ve tried, including M1. Training is marginally faster on M1 than intel, but clearly not as fast as a dedicated GPU (and not taking advantage of the M1 machine learning abilities).  So I’m assuming @Benthealchemist that you are asking about engaging the M1 GPU. AFAIK, no one has that working yet.

**Comment by Benthealchemist** [comment]
@backyardbiomech I installed the DLC-CPU but the issue seems to be with tensor flow. If I try to run either DLC or TF I get an illegal hardware instruction error. 
May I ask which version of TF you usually run on your mac installs (CPU only)?

**Comment by outlace** [comment]
I also get the illegal hardware instruction error on my macbook air 2020 with M1 chip when trying to import deeplabcut

**Comment by AlexEMG** [comment]
Btw, this has been solved for a while: https://github.com/DeepLabCut/DeepLabCut/blob/8fc83b64a04a8e0e962fd51a30262237d2bb5695/docs/recipes/installTips.md#deeplabcut-m1-chip-installation-environment-instructions
