### ISSUE TITLE
What loss is small enough?

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#11]
Hello,

The training has been running for 24h or so, and I'm wondering what loss is small enough. I'm now at 

`iteration: 944000 loss: 0.0005 lr: 0.001`

Can I just abort that now (Ctrl+C) and take the weights as they are or do I need to wait until the end of the training?

Cheers

**Comment by MMathisLab** [comment]
Hello! Yes, you can quit by control-c or kill in top [for unix]; (it will stop at ~1M anyhow if you didn’t change this parameter). 

Also, what loss is small enough? 

This is a more tricky question than one might think, because the loss is not straightforward to interpret (as it depends on how noisy labels are, size of bodyparts/image, etc. ). 

However, practically speaking you can check if the loss plateaus (check Figure 2 in our preprint). For most cases we have worked on, the loss only slowly decays after 200,000 trials. So you can def. also stop earlier and test (or save multiple snapshots and test...). Keep in mind that you can then also restart if from any snapshot...
