### ISSUE TITLE
Labels are not created after using the GUI (fixed)

### ISSUE THREAD

**Issue by saritma** [DeepLabCut/DeepLabCut#116]
Hi,
I'm using windows 10 with anaconda env.  and the new version of DLC.
 -  chrome
 
I'm trying the demo for my data. 
The GUI worked and labeled the points, but in the next step: "check the labels" the folder that created- "labeled" is  empty.

what can I do to change that?
Thank you!

**Comment by imagejan** [comment]
This is an issue with the resulting file paths being invalid on Windows. See #117 for a fix.

**Comment by AlexEMG** [comment]
Thanks @imagejan > Accepted your PR. @saritma, please test it with the latest version.

**Comment by MMathisLab** [comment]
*from Slack group: * when I run `deeplabcut.check_labels()`, the function creates a folder with the name videoname_labelled, and it creates the images with the overlaid labels, but it then saves these images in the folder videoname instead of videoname_labelled, thus overwriting the original frames.

FIXED with https://github.com/AlexEMG/DeepLabCut/pull/117 !!!

**Comment by saritma** [comment]
I'm sorry, I didn't understand the suggestion for solving the problem in #117. Can you be more specific about the steps?

**Comment by MMathisLab** [comment]
You can just download the latest code here and it is fixed! :) It’s not updated in the pip package yet, but will be later today.
