### ISSUE TITLE
Issues regarding tracking

### ISSUE THREAD

**Issue by CastielFracs** [DeepLabCut/DeepLabCut#1196]
Currently I am using an Ubunte (Linux) computer with Anaconda and Deeplabcuts newest version (v2.10.2).

Recently I started using DeepLabCut in order to track old recordings in which 2 mice are present within frame to track their movement, thus I have been using the multi-animal function. After labelling 700-800 frames, I was told by people it would be plenty to get a proper response and proper tracking in order to get the program working with 1.000.000 iterations. Sadly enough there is a high amount of switching, sometimes from one frame to another and back or in general. Furthermore, points seem to drift even with the contrains put by using the skeleton function. Are there any tips in order to improve this without refining high amounts of tracklets manually?

**Comment by AlexEMG** [comment]
The paper & code updates are imminent...

**Comment by CastielFracs** [comment]
I dont really know how to do that. I am using the program not running the
codes separately...

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op do 22 apr. 2021 om 20:49 schreef Alexander Mathis <
***@***.***>:

**Comment by jeylau** [comment]
@CastielFracs, you won't have to do much, just wait for the update coming soon that will improve tracking (among many other things) 😊

**Comment by MMathisLab** [comment]
@CastielFracs it is now updated, please see the new documents, and if you have questions or further issues, please post below (so we can track it here).

**Comment by CastielFracs** [comment]
Thank you, I will check the update out today :)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op zo 2 mei 2021 om 20:41 schreef Mackenzie Mathis ***@***.***

**Comment by CastielFracs** [comment]
Dear Team DeepLabCut,

Recently I have installed the latest update which you have released. During
training it keeps giving a certain error which online states its okey or
that someone else is closing the queue, but thats not the case here. This
error occurs at 200.000 iterations if I want to train my network for
1.000.000 iterations and directly after 1000 iterations if I am trying to
train my network for a 1000 iterations. The error message is shown below
(image 1 and 2). Could you tell me what is going on and how to fix this? (I
already looked at the GPU usage, which had enough space to run
the training) I also tried to continue since it states that the network is
trained by evaluating the network, but it gives an ModuleNotFoundError: No
module named 'easydict'....
[image: image.png]
[image: image.png]
Kind regards,

CastielFracs


Op ma 3 mei 2021 om 12:46 schreef A Vdlp ***@***.***>:

**Comment by CastielFracs** [comment]
The issue regarding easydict has been resolved, but it this in general how
it is supposed to be now with the iterations? I have seen on various forums
that parameters are overwritten, but this has never been the case before in
my files, hence why I am emailing you. Sorry if this is not the normal way
of doing things, I can also make a post on a forum if you prefer.

Op di 1 jun. 2021 om 11:30 schreef A Vdlp ***@***.***>:

**Comment by backyardbiomech** [comment]
Since you are running maDLC, I believe that the maximum iterations are limited to 200k even if you set the number higher (see [docs](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md)). If you need more iterations, you can run for 200k, then train again but set the last checkpoint as your `init_weights`, and the next round of training will start from where the previous round finished.

More importantly, you shouldn't need to train that much. The fact that you're having tracking and switching problems after training that much suggests that either your video is not clear, there is an error in your labelling, or you have skipped some other steps. 

Did you check all of your labels and make sure there aren't any improperly placed labels? Even 1 out of 700 can cause problems. Did you only label clearly visible landmarks, or did you guess where landmarks are even when occluded?

When you created your training data set, did you crop images and labels? This will let you use a larger batch size.

What batch size are you using? If you are using batch size of 8 for training (set in `pose_cfg.yaml` in train folder, not in the config.yaml file), you should only need 20k-50k iterations. If your GPU has 12 GB, you should be able to use batch size of 8 for images cropped to 400x400.

During training, does the loss plateau? At what value? What are the evaluation results? If after training to 200k loss doesn't plateau below 0.1 (or 0.01), and evaluation results show rmse higher than 2-5 pixels, then you probably have errors in your labels.

**Comment by CastielFracs** [comment]
Dear Brandon Jackson,

Using this program before, I was able to run 1M iterations, is this limited
since the latest update?

I have gone over the labels and they appear to be fine, will recheck it
later today again. I did not label landmarks that were unclear.

I have not used crops because my boss stated that this was probably the
cause of various issues regarding the marks moving far away from the mice.
Would you recommend them instead?

Currently I am using a batch size of 8, the GPU only has 8 gb though.

During training loss value plateaus at the value of 0.0007, so I reckon
that the labels are proper then? I do have 1 video in which a part of the
view is blocked by a black bar, does this in general affect things or
should it still run properly?

Thanks so much for your help.

Kind regards,

CastielFracs

Op di 1 jun. 2021 om 16:09 schreef Brandon Jackson ***@***.***

**Comment by backyardbiomech** [comment]
@CastielFracs , yes the 200k iteration limit was set in a recent update, but it's there in part because maDLC projects are expected to use cropping, and thus larger batch sizes, and therefore not need that many training iterations. I have very complicated videos of flying birds against messy backgrounds and never have to train more than 50k iterations at batch size of 8 (25k at batch size of 16). Yes, I would crop before creating the training dataset (but you might create a copy of the whole project as a backup before running that), and then try a higher batch size (10, or 12), then train for 50k iterations.

That loss is very good. What are the rmse following evaluation of the network? 

It's also hard to tell what could be happening without seeing the video. Can you post a screen grab of a video to GitHub? Or maybe just one of your labeled images produced by check labels?

**Comment by CastielFracs** [comment]
Dear Brandon Jackson,

I do not recall the rmse values, but this already helped a lot. I will try
to run it with these settings and just exclude the obstructed videos.

You have been an extreme help, thank you so much!

Kind regards,

CastielFracs

Op di 1 jun. 2021 om 16:38 schreef Brandon Jackson ***@***.***

**Comment by CastielFracs** [comment]
Dear Brandon Jackson,

I have currently run a new data set all made within the 2.rc2.1 update
(labelled all the frames again (200 should in general be enough right?),
created dataset etc) with your proposed batch size but instead with 10.000
iterations to test whether the message regarding 'skipping cancelled
enqueue attempt with queue not closed' and the following 'Caused by op
'fifo_queue_enqueue', defined at...' would persist as previously mentioned.
This occurred again but the program appears to work, but the quality was
not as high at 10.000 (as expected, I will give an update and video once I
have trained it at higher iterations because I feel like this problem might
persist), so is this 'error' that will affect my results or is this just
the newest update message stating that it's done with training?

Furthermore, I was wondering if your team is going to do a little
video/blog post on the new settings availability in the refine tracklet and
analyze video tabs, I observed various parameters regarding switching etc
which would be quite useful to have more information about the way it
affects the network.

Also, it appears that new labeled frames made in the newest update version
do not require easydict, while the network I trained before the update
cannot be evaluated without easydict, do you know what happens there?

Kind regards,

CastielFracs



Op di 1 jun. 2021 om 16:38 schreef Brandon Jackson ***@***.***

**Comment by backyardbiomech** [comment]
That error is just the normal end of training error. If it reaches your `max_iters`, and the snapshot is saved, then you can ignore any errors during training.

To clarify, I'm not a developer of DLC, just a heavy user trying to help other users (and to help the actual developers to focus on development rather than support).

I believe that the concepts behind those settings are described in the [latest preprint](https://www.biorxiv.org/content/10.1101/2021.04.30.442096v1) that was released with `2.2rc1`. I think there will be some tutorials or more advanced sample projects in the future.

Lots of things changed between the 2.1+/2.2b and 2.2rc1. I didn't even bother trying to analyze new videos in rc1 with my previous models in any of my ongoing projects. I went back to creating training datasets, and training fresh models. Plus that let me take advantage of the DLCresnet structure.
