### ISSUE TITLE
New Advanced Labeling across cameras mode='match' Issue

### ISSUE THREAD

**Issue by evianapetropoulou** [DeepLabCut/DeepLabCut#1211]
**Your Operating system and DeepLabCut version**
OS: Windows 10 Professional 1803
DeepLabCut: 2.1.10.4
Anaconda Env used: 2020.11 Version

**Describe the problem**

Hello,
I am currently working on a 3DLC Project and I am trying to use the New Advanced Labeling Across Cameras functions, however I am having some trouble. 

I created a 3D Project and calibrated my 2 cameras, although once I check the undistortion, I get black images in return in the undistortion file. Please find attached the checkerboard_3d, original_image and undistorted_points. 
1) Original_Image: https://www.dropbox.com/s/jy3848dutqewnh0/Original_Image.png?dl=0
2) Undistorted_points: https://www.dropbox.com/s/csq9bpancd2yr90/undistorted_points.png?dl=0
3) Checkerboard_3d: https://www.dropbox.com/s/zq9vw8wx6v79uve/checkerboard_3d.png?dl=0

I would like to inform you that my setup is orthogonal, and based on the issue #1128, this may be the reason why I am getting black pictures in result. I still have not tried the triangulation part to see if it works, though. Instead, I wanted to try the new Advanced Labeling Across Cameras functions. 

I succeeded in extracting the frames from the videos of camera-7, however once I try the function dlc.extract_frames(config_path_camera-8, mode='match', config3d=config_path3d, extracted_cam=0), I do not get any of the matched frames in return. 
I checked the config file paths many times but I can not detected any issue there. Also, the camera names are correct in the config files. 

Here are 2 screenshots of the code in the terminal : 

![image](https://user-images.githubusercontent.com/82345816/116695549-102b7d80-a9c1-11eb-954b-aac989d0f601.png)
![image](https://user-images.githubusercontent.com/82345816/116695608-23d6e400-a9c1-11eb-88d5-b7d40b060987.png)

Please let me know if you would like extra documentation and thank you in advance! 

Best, 
Eviana

**Comment by MMathisLab** [comment]
hi @evianapetropoulou without triangulation working, this will not work.

**Comment by evianapetropoulou** [comment]
Thank you so much for the quick reply!

I thought that triangulation was the 4th step, that's why I didn't try it out (on the website with the new functions documentation, only the steps 1-3 are said to be needed in order to proceed to the dlc.extract_frames step). 

Have a nice day,
Eviana

**Comment by MMathisLab** [comment]
sorry, I was unclear :) I mean that the camera-calibration should work, such that one can triangulate :)

**Comment by evianapetropoulou** [comment]
Oh I see! I guess I need to solve the undistortion problem then, by changing my camera setup. 

Thanks a lot for the clarification! :)

**Comment by MMathisLab** [comment]
sounds good! I will close, but if you have issues, please post back on this thread in the future!

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi, sorry to re-open this issue.

I was trying the `method='match'` parameter in `deeplabcut.extract_frames`  and got a similar problem as above "I do not get any of the matched frames", although I am trying to overwrite the already extracted frames for the second camera.

I am working with mp4 videos, and noticed in [`deeplabcut/generate_training_dataset/frame_extraction.py`](https://github.com/DeepLabCut/DeepLabCut/blob/74329d85a26889afea0f6dae1af54522338155ca/deeplabcut/generate_training_dataset/frame_extraction.py) that `.avi` is hardcoded in [line 542](https://github.com/DeepLabCut/DeepLabCut/blob/6eefd0ccbc320daa76fb07c767209a37cc6fe40e/deeplabcut/generate_training_dataset/frame_extraction.py#L542). Is this intended?

The `video_dir` is also hardcoded to `os.path.join(project_path, "videos/")` in [line496](https://github.com/DeepLabCut/DeepLabCut/blob/6eefd0ccbc320daa76fb07c767209a37cc6fe40e/deeplabcut/generate_training_dataset/frame_extraction.py#L496), instead of reading the path from the `video_sets:` such as in `mode == "manual"`.

## EDIT

Yup, using '.avi' videos instead solves the issue, I get matching frames now!
