### ISSUE TITLE
TypeError when running testscript.py

### ISSUE THREAD

**Issue by tyyin12** [DeepLabCut/DeepLabCut#1265]
OS: Windows 10
DeepLabCut Version: 2.1.10.4
Anaconda env used: Yes

**Describe the problem**

Hi, I am new to DeepLabCut and while I was running the testscript.py file to check my installation, I ran into this problem
TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'
I followed the tutorial video step-by-step and I am not sure how to fix this. Any advice or help is much appreciated. Thanks!

**How to Reproduce the problem**
1.  open Anaconda Prompt
2.  Activate DLC-CPU
3.  run python testscript.py

![image](https://user-images.githubusercontent.com/84589354/119176542-1640d700-ba20-11eb-8d70-becdbb6834ad.png)

**Comment by jeylau** [comment]
Hey @Potato1214, it is just that your testscript is ahead of your installation; if you grab the latest version from `master`, you'll have no problem 😊

**Comment by MMathisLab** [comment]
Here is how to grab the latest code, btw! 

https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code

**Comment by tyyin12** [comment]
Thanks!

**Comment by pondposaphiwat** [comment]
> I cloned the most recent code but this got this exact same error (TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'). Are there any other solutions you can think of?

<img width="712" alt="Screen Shot 2564-05-25 at 08 43 22" src="https://user-images.githubusercontent.com/70335919/119527611-af6a4780-bdaa-11eb-998b-32333703793b.png">

**Comment by tachposa** [comment]
> > I cloned the most recent code but this got this exact same error (TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'). Are there any other solutions you can think of?
> 
> <img alt="Screen Shot 2564-05-25 at 08 43 22" width="712" src="https://user-images.githubusercontent.com/70335919/119527611-af6a4780-bdaa-11eb-998b-32333703793b.png">

OS: MacOS (Mojave)
DeepLabCut Version: 2.1.10.4
Anaconda env used: Yes

Describe the problem

TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'
I followed the tutorial video step-by-step.

How to Reproduce the problem
Steps to reproduce the behavior:

open Anaconda Prompt
Activate DLC-CPU
run python testscript.py

**Comment by jeylau** [comment]
Something's wrong with your installation. If you follow the tutorial or install DLC via our conda environment files, the version should be 2.2rc1, not 2.1.10.4. Since you've already cloned the repo apparently, you could try the following:
```
conda activate DLC-CPU
cd DeepLabCut
pip install .
```
and it should work fine.

**Comment by MMathisLab** [comment]
Indeed, please follow the instructions here, and when you check the version it should be 2.2rc1 as Jessy points out: https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code

**Comment by tachposa** [comment]
> Indeed, please follow the instructions here, and when you check the version it should be 2.2rc1 as Jessy points out: https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code

Thank you for your response! I have followed the steps and it is now showing this error instead. What should I do?

<img width="875" alt="Screen Shot 2564-05-25 at 13 14 45" src="https://user-images.githubusercontent.com/70335919/119562688-78b91080-bd5b-11eb-8901-1947a3bece06.png">

**Comment by shahmili** [comment]
Interesting... I had the same problems as you and I am now stuck with this as well.  Any ideas on how to fix?  Thanks!

**Comment by lachioma** [comment]
I had the same issue but I could fix it.

I freshly installed DLC-GPU. The DLC version was 2.1.10.4. The testscript.py was giving the error `TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'`

Then I ran:
```
conda activate DLC-CPU
cd DeepLabCut
pip install .
```
which provided DLC version 2.2rc2.

At this point, the testscript.py completed successfully.

**Comment by suhjinlee** [comment]
Hi! I am a widnows os user trying to use the DLC-GPU and faced a similar problem where the DLC version was 2.1.10.4 and running the testcscript.py gave the TypeError: analyze_videos() got an unexpected keyword argument 'allow_growth'.
The problem is when i updated the DLC to the 2.2rc1 and try to run the testscript again, i face the "error [WinError 126] The specified module could not be found".
Could someone guide me how to solve this? Thank you!

**Comment by jeylau** [comment]
Hi @suhjinlee! What is the module that could not be found? Can you post the full error?

**Comment by suhjinlee** [comment]
@jeylau Here is the full error! Thank you!
![image](https://user-images.githubusercontent.com/43252216/121214060-c1bfa780-c8b9-11eb-98a9-8aa3df7253e1.png)

To give more details. 
I created a environment using conda create -n DLC python=3.7 tensorflow=1.13.1
with cuda 10. cudnn 7.4.2
and then installed deeplabcut by pip install deeplabcut and adding pip install -U wxPython<4.1.0

**Comment by jeylau** [comment]
Another user reported the same error https://github.com/DeepLabCut/DeepLabCut/issues/1292. Try `pip install shapely` and that should work; otherwise, create your conda environment from the configuration files we provide in DeepLabCut/conda-environments, this is safer. 😃

**Comment by suhjinlee** [comment]
@jeylau  Thanks for the quick response. the install shapely method didn't work so i created a new environment with the DLC-GPU.yaml file. With this route, I can import deeplabcut initally without error in ipython. however, when I try to run the testscript.py, it still gives me this error.
![image](https://user-images.githubusercontent.com/43252216/121313778-b1eba600-c941-11eb-85f4-4f703de6b457.png)

I tried to download the python.app referring to this post https://github.com/DeepLabCut/DeepLabCut/issues/1218#issuecomment-853280085
but get error of this
![image](https://user-images.githubusercontent.com/43252216/121314077-fa0ac880-c941-11eb-8805-8245ebc2d951.png)

it also seems sth related to this post https://forum.image.sc/t/no-module-named-deeplabcut-windowsgpu/29067 
because i cannot find deeplabcut in the conda list.....in the environment even though i am in the admin conda powershell and downloaded the deeplabcut with ./reinstall.sh

**Comment by backyardbiomech** [comment]
The `conda install python.app` fix is specific to MacOS, so that result is not surprising.

Deeplabcut does not show if your run `conda list` in your env? That means that something failed with the deeplabcut installation during the env creation, but assuming that the rest of env was properly created, I think you should be able to run `pip install 'deeplabcut[gui]'==2.2rc2` within your env. 

Also, instead of posting screen grabs of errors, it's much easier to read if you copy and paste the text, between two rows of three tilde marks. In other words

\`\`\`
paste error here
\`\`\`

**Comment by suhjinlee** [comment]
@backyardbiomech Thank you. Now it does show on the conda list and can run the testscript.py. I have some other errors but will look online first to see how i can fix them.

And thank you for letting me know how to paste the error. i will do that moving on!
