### ISSUE TITLE
desktop freezes after few hours of analyzing videos

### ISSUE THREAD

**Issue by salvatoreNRIM** [DeepLabCut/DeepLabCut#1336]
**Your Operating system and DeepLabCut version**
I am using windows 10 on a dell desktop (Precision 5820 Tower Workstation) with Anaconda environment, deeplabcut 2.2rc2.
GPU Quadro RTX 4000, CUDA 10, Nvidea driver 462.59.
The issue I keep running into is that after training the network and try to analyze the folders with the videos the desktop will stop working after 1 hour (sometime in less, sometime in more time). While the code is running it works fine (all the files are created in the appropriate location), and there is no error log in the jupyter notebook code. I tried to downgrade to CUDA 9, and appropriate driver, and resintalling deeplabcut, but that did not solve the issue. Finally I tried to reduce the global scale to 0.6, suspecting that the issue is that the network is using too much GPU power. But again no success. 
I tried to use the same dlc model on a different desktop and it works fine, so I think the issue is in the communication between dlc and the GPUs in my desktop. But I am running out of ideas at this point. Does anyone have some suggestion on what the issue might be?

**Comment by KonradDanielewski** [comment]
Could you elaborate more on what exactly do you mean by that the desktop stops working? Does it freez (and you have to reset), go black (like goes to sleep), just stops the code with no output?

**Comment by salvatoreNRIM** [comment]
It freezes and I have to reset. It does produce output though up to before freezing. Also it can occur while I'm actively working on the computer.

**Comment by KonradDanielewski** [comment]
Is there some error printed before it freezes? Did you check what the load looks like on GPU and CPU? I would suspect that it is not connected to DLC per se, maybe the PSU has a problem with handling the heavy load in a stable way, or the GPU overheats? If I were you, I'd check the load and log temperature. 

Since you already tried different drivers I would go in this direction (though one more thing you could try is using DDU for proper display driver removal)
