### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by lkaesberg** [DeepLabCut/DeepLabCut#1353]
OS: Ubuntu 18.04.5 LTS
DeepLabCut Version: 2.1.10.4
Anaconda env used: DLC-GPU

**Describe the problem**

I train my DeepLabCut models on a GPU cluster server, but I have the problem that it has a very high CPU usage. I can see that it uses the GPU but still the CPU usage is about 1000%. Is there a way to limit the CPU usage? I already tried this : https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core
That was recommended in another thread here, but it doesn't work for me

**Screenshots**
![image](https://user-images.githubusercontent.com/33939116/123406982-c23f8a00-d5ab-11eb-8e15-de6cbfb9e2cf.png)

**Comment by MMathisLab** [comment]
if your images are very large, this could be the cause; try using cropandlabel before creating a training set

**Comment by AlexEMG** [comment]
Due to the augmentation, filling the queue... especially for large images a lot of compute is helpful, which is why it uses multiple cores (& multiple cores increases speed). 

If you want to change this behavior, check this out: https://askubuntu.com/questions/483824/how-to-run-a-program-with-only-one-cpu-core
