### ISSUE TITLE
XDisplay Error Running DLC on an HPC

### ISSUE THREAD

**Issue by rahulgprabhu** [DeepLabCut/DeepLabCut#1389]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

Preface: I'm a complete computer science amateur and many of these CompSci words are just incomprehensible to me. 

**Your Operating system and DeepLabCut version**

Mac OS, Linux HPC, DLC v2.1.10.4

**Describe the problem**

We are in the process of re-labelling outlier frames. We do this using DLC on an HPC. I was able to extract the outlier frames using kmeans clustering, and when I type "deeplabcut.refine_labels(config_path)", I get an XDisplay error. I found one solution online about changing the display pointed to in the config file, but there is nothing in our config file pointing to an XDisplay. 

Code:

In [2]: config_path = '/mnt/research/hhorch/rprabhu/project_dlc/190708-Julie-201
   ...: 9-07-08/config.yaml'                                                    

In [3]: deeplabcut.refine_labels(config_path) 

Output Error:

An exception has occurred, use %tb to see the full traceback.

SystemExit: Unable to access the X Display, is $DISPLAY set properly?

/mnt/local/python-venv/dlc/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by MMathisLab** [comment]
hi @rahulgprabhu so typically for HPC you don't have a screen, i.e. you run scripts through a terminal. Does yours allows for a screen? Can you explain how you are running this (in a Docker container? conda?); the config.yaml for DLC won't be the solution, but if your docker/HPC allows for a screen, you can edit the dockerfile. Otherwise, this step does not require a GPU; you can download your project locally to any laptop, label, run `merge` then re-upload, create training set, and train again
