### ISSUE TITLE
`plot_trajectories` ValueError: Unrecognized track_method

### ISSUE THREAD

**Issue by h1408** [DeepLabCut/DeepLabCut#1424]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

MacOS 10.15.7. DLC version 2.2rc2 for using GUI to label frames, DLC version 2.1.104 Google Colab for training network and analyzing videos.

**Describe the problem**

I get an error when trying to run the Plot trajectories step in the colab notebook 

Please place code inside this:

<details><summary>Code output</summary><p>

```
Analyzing all the videos in the directory...
Loading  /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/7357 58 OFT CNO001.wmv and data.
No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video 7357 58 OFT CNO001 and scorer DLC_resnet50_oftJul18shuffle1_10000.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/plotting.py in plot_trajectories(config, videos, videotype, shuffle, trainingsetindex, filtered, displayedbodyparts, displayedindividuals, showfigures, destfolder, modelprefix, track_method, imagetype, resolution, linewidth)
    257             df, _, _, suffix = auxiliaryfunctions.load_analyzed_data(
--> 258                 videofolder, vname, DLCscorer, filtered, track_method
    259             )

4 frames
FileNotFoundError: No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video 7357 58 OFT CNO001 and scorer DLC_resnet50_oftJul18shuffle1_10000.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxiliaryfunctions.py in load_detection_data(video, scorer, track_method)
    768         tracker = "el"
    769     else:
--> 770         raise ValueError(f"Unrecognized track_method={track_method}")
    771 
    772     filepath = os.path.splitext(video)[0] + scorer + f"_{tracker}.pickle"

ValueError: Unrecognized track_method=
```
</p></details>

**How to Reproduce the problem**
1. Use GUI to create project, extract and label frames
2. Use colab notebook to train and evaluate results
3. try to run the plot trajectories and get the error

**Comment by jeylau** [comment]
Hey! If that is with a multi-animal project, you need to specify what tracking method you used with `deeplabcut.plot_trajectories(..., track_method='ellipse' or 'box')`

**Comment by h1408** [comment]
Hello, thanks for your reply! I tried doing that but still get the error message below. It seems like it's looking for 'unfiltered data files' but I don't know what I need to do differently to get those. Any thoughts on why this might be happening? 

> Analyzing all the videos in the directory...
> Loading  /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/OFT 2089 90001.wmv and data.
> No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video OFT 2089 90001 and scorer DLC_resnet50_oftJul18shuffle1_10000 and ellipse tracker.
> No detection data found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video OFT 2089 90001, scorer DLC_resnet50_oftJul18shuffle1_10000, and tracker ellipse
> Make sure /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/OFT 2089 90001.wmv was previously analyzed, and that detections were successively converted to tracklets using "deeplabcut.convert_detections2tracklets()" and "deeplabcut.convert_raw_tracks_to_h5()".
> Loading  /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/7357 58 OFT CNO001.wmv and data.
> No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video 7357 58 OFT CNO001 and scorer DLC_resnet50_oftJul18shuffle1_10000 and ellipse tracker.
> No detection data found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video 7357 58 OFT CNO001, scorer DLC_resnet50_oftJul18shuffle1_10000, and tracker ellipse
> Make sure /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/7357 58 OFT CNO001.wmv was previously analyzed, and that detections were successively converted to tracklets using "deeplabcut.convert_detections2tracklets()" and "deeplabcut.convert_raw_tracks_to_h5()".
> Plots could not be created! Videos were not evaluated with the current scorer DLC_resnet50_oftJul18shuffle1_10000.

**Comment by h1408** [comment]
Hello, thanks for your reply! I tried this method but got an error about not having any unfiltered data, so I added this line to the colab notebook before plot trajectories:
`deeplabcut.filterpredictions(path_config_file, videofile_path,videotype='.wmv', shuffle=1, trainingsetindex=0,  filtertype='arima', p_bound=0.01, ARdegree=3, MAdegree=1, alpha=0.01)`

However, I get this message after trying to run that:

> Analyzing all the videos in the directory...
> Filtering with arima model /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/7357 58 OFT CNO001.wmv
> No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video 7357 58 OFT CNO001 and scorer DLC_resnet50_oftJul18shuffle1_10000.
> Filtering with arima model /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos/OFT 2089 90001.wmv
> No unfiltered data file found in /content/drive/My Drive/deeplabcut/oft-hs-2021-07-18/videos for video OFT 2089 90001 and scorer DLC_resnet50_oftJul18shuffle1_10000.

I've attached a screenshot of what my videos folder looks like. Any thoughts on why this might be happening? 
![Screen Shot 2021-07-21 at 3 32 49 AM](https://user-images.githubusercontent.com/80368001/126475130-0e231e16-3241-42d9-8858-c09a4ec9aa61.png)

**Comment by backyardbiomech** [comment]
There are three problems I can see here.
1. This is what is directly causing your problem: You don't state it, but I can tell from the files created that you are running a multi animal project. With maDLC projects, after `analyze_videos`, you have to run `convert_detections2tracklets` and `stitch_tracklets` **before** `plot_trajectories`, as stated in the [maDLC User Guide](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html) and in the [maDLC Colab example notebook](https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb). `stitch_tracklets` will produced the unfiltered files you need for `plot_trajectories`. You should not filter the data before plotting trajectories when you're evaluating your model's tracking ability, but you should filter data once you're happy with your model for data analysis.
2. As a general suggestion, avoid spaces in your file names. It doesn't always cause problems, and it's not causing this problem, but it's good practice when dealing directly with computer code.
3. You are running multiple versions of DLC. The commands I describe above, the user guide, and the colab example, are all based on `2.2rc3` with significant changes since 2.1.10.4. You should install 2.2rc3 at least in your colab notebook, recreate the training dataset (you can then use the new dlcrnet models which have worked really well for me), retrain, convert (using the ellipse tracker) and stitch. In fact, the ellipse tracker wasn't introduced until 2.2rc1, so 2.1.10.4 would throw an error for that tracker method anyways.

**Comment by MMathisLab** [comment]
@backyardbiomech is 100% spot on. 

Note, I would use the latest COLAB notebook, as it will install the latest DLC already: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

**Comment by YoaviA** [comment]
I'm having this problem in a single animal project
