### ISSUE TITLE
How to extract DEEPLABCUT 3D MODEL as *.pb 

### ISSUE THREAD

**Issue by rrimyyu** [DeepLabCut/DeepLabCut#1432]
Hi! I am RIM. 

I'd like to extract DEEPLABCUT 3D MODEL(*.pb) because I want to apply that model to DLC-LIVE or real-time video. 
How should I get that MODEL as *.pb file? 

Thank you for your support. :))

**Comment by KonradDanielewski** [comment]
I don't think I follow. 3D reconstruction uses normal model trained on 2D data. I may be wrong, but I think that in order to use DLC-Live this way you'd have to run separate stream of pose estimation for each camera and triangulate those in real time.

Anyway, the model you use is a model for 2D data

**Comment by MMathisLab** [comment]
Yep! right now DLC supports 2D neural networks; so the `dlc.model_export...` is how to do it, and in the camera gui you can edit this to run 3D, if needed
