### ISSUE TITLE
Analyze_videos() creates no output after retraining [colab]

### ISSUE THREAD

**Issue by PatrickHonma** [DeepLabCut/DeepLabCut#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After refining labels and retraining the network, we are having a trouble analyzing videos again. When running the analyze_videos() function, the output runs through without any errors:
![Analysis Error](https://user-images.githubusercontent.com/85576484/129796441-c9f2efcd-75b1-4ed1-a162-7f71ad6f7885.PNG)

However, the videos folder (default destination folder; also tried changing the destfolder) contains no .h5, csv, or pickle files. I have tried moving the videos to a different path, converting the .mp4 videos into .MOV or saving to another .mp4, and even retraining the network. I still run into the same issue where the analyze videos goes to completion on all videos in the path but does not output any results. I have used the same method of refining/retraining/analysis in the past for another cohort of animals and didn't run into this problem.

### Operating System

Windows 10/Google Colab

### DeepLabCut version

2.2rc3

### DeepLabCut mode

single animal

### Device type

Google Colab Pro

### Steps To Reproduce

1. Refine and retrain network
2. run analyze_videos() --> no results

### Relevant log output

```shell
Starting to analyze %  /content/drive/Shareddrives/DeepLabCut_SRM_SharedDrive/ProjectFolders/Vanessa_Project_Folders/IKKBetaCA-Pilocarpine-OF_21vids_Atmpt3-VU-2021-07-26/videos/Trial61.mp4
/content/drive/Shareddrives/DeepLabCut_SRM_SharedDrive/ProjectFolders/Vanessa_Project_Folders/IKKBetaCA-Pilocarpine-OF_21vids_Atmpt3-VU-2021-07-26/videos  already exists!
Loading  /content/drive/Shareddrives/DeepLabCut_SRM_SharedDrive/ProjectFolders/Vanessa_Project_Folders/IKKBetaCA-Pilocarpine-OF_21vids_Atmpt3-VU-2021-07-26/videos/Trial61.mp4
Duration of video [s]:  1202.32 , recorded with  25.0 fps!
Overall # of frames:  30058  found with (before cropping) frame dimensions:  1280 960
Starting to extract posture
Cropping based on the x1 = 230 x2 = 695 y1 = 510 y2 = 965. You can adjust the cropping coordinates in the config.yaml file.
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
2021-08-17 20:31:07.791858
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
If you've tried re-encoding videos so that you know they are not corrupted, I think this is a colab (or Google Drive) issue (see [this](https://github.com/googlecolab/colabtools/issues/287) long-running issue), where larger files in the colab cache are not immediately (or ever) written to the drive.

You might try the suggested fix:
```
from google.colab import drive
drive.flush_and_unmount()
```
 after running `analyze_videos`.

**Comment by PatrickHonma** [comment]
I tried running these lines after analyze_videos, but I am still encountering the same issue.

**Comment by rhgoo** [comment]
Hello, I'm encountering similar issues except with create_labeled_videos. Analyze videos works fine for me (the .h5 and metapickle are loaded onto the folder) but I don't see any labeled videos. I too tried the solution to import from colab and then flush/unmount my Drive but still no progress.

**Comment by backyardbiomech** [comment]
@PatrickHonma, In your output, your missing the "iterations" line (see the second line in the code below):

```
Starting to extract posture
2346it [02:16, 17.23it/s]Saving results in /content/cloned-DLC-repo/examples/openfield-Pranav-2018-10-30/videos...
The videos are analyzed. Now your research can truly start!
```

Did you see a progress bar as it analyzed each video? 30k frames should take a couple of minutes to analyze. If not, then it never loaded the full video. The fact that it finds the frame numbers for each suggests that your paths are all correct, and that it can see the files themselves. But it might not be able to actually load the frames. That could still be a drive/colab issue, or your video files could be corrupted.

You can easily check the videos with

```
deeplabcut.check_video_integrity(video_path)
```

`video_path` is the path to a single video, not a list of all videos or a path to a directory.  E.g., you could try adding a colab cell with the following in your notebook:

```
video_path = "/content/drive/Shareddrives/DeepLabCut_SRM_SharedDrive/ProjectFolders/Vanessa_Project_Folders/IKKBetaCA-Pilocarpine-OF_21vids_Atmpt3-VU-2021-07-26/videos/Trial61.mp4"

deeplabcut.check_video_integrity(video_path)
```

If your video is fine, the cell will run "for a while" (it will load the video frame by frame) without any feedback, then stop running. If it gives no warnings and stops itself, your video is probably ok. If it gives warnings, then you should re-encode the video.

That said, given that @rhgoo is having an apparently similar problem but with a different stage suggests some colab issue (but many aren't having any problems, and I just ran a test without a problem, so it's not a universal deeplabcut or colab issue).

You could also try one video at a time, giving the full path to the video in square brackets, rather than a directory of videos. 

Lastly, make sure you're passing `videotype` correctly. It should be "mp4" or "avi" without a ".". That can cause some unpredictable behavior.

**Comment by PatrickHonma** [comment]
@backyardbiomech , I don't see the usual progress bar during the analyze_videos() step that I normally see, which made me think something is wrong. I just tried the check_video_integrity function on one of the videos and it ran for 2:39 min before stopping without any errors (seems like the video is ok?).

I also tried running the analyze videos step with only one video and with videotype "mp4", but I am still running into the same problem.

**Comment by rhgoo** [comment]
> ```
> deeplabcut.check_video_integrity(video_path)
> ```

I don't know if it's because my video files are actually corrupt, but I'm getting an error when I run the code to check video integrity.

I also recreated a new project and created an entirely new training set but still no labeled video. Analayze and plot_trajectories work fine because the files are there.
![vidintegrityerror](https://user-images.githubusercontent.com/86977704/131030209-625e4fa1-2cc1-4521-a9fa-079516141392.png)

**Comment by backyardbiomech** [comment]
@PatrickHonma, yes, no output from checking integrity suggests that the video can be read fine (that code uses the same frame-by-frame code to load the video as the analyze_video code); the fact that it took 2:39 suggests it actuall did run fine.  But since you don't see the progress bar during analysis, though, indicates that deeplabcut in colab isn't loading the actual video. Did you run the integrity check in colab or on your local computer? I think the only way to troubleshoot this that I can think of is to run the integrity check on colab, and to run the video analysis on your local computer (which will be slow without a GPU, so choose the shortest possible video that fails on colab). There is also a [memory leak](https://github.com/DeepLabCut/DeepLabCut/issues/1468) in opencv, which seems to manifest differently in the issue report linked, but could be related to this since your videos are fairly long.

@rhgoo - that seems to be a problem with colab reading and writing files. Try running the check integrity function locally.

**Comment by PatrickHonma** [comment]
@backyardbiomech I ran the integrity check on colab, so I do think it may be a problem with colab. I will continue looking into this. Thank you!

**Comment by jeylau** [comment]
FWIW, all testscripts and `check_video_integrity` work on Colab in my hands. Some online suggested to try `drive.flush_and_unmount()` to sync data written to the local VM's disk cache of your Drive-mounted folder back to Google Drive. I'm not sure this helps but may be worth giving a try!
