### ISSUE TITLE
matplotlib vulnerability in extract_frames() function

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#149]
In *DeepLabCut* version (2.0.1), the file *frame_extraction.py* contains the function *extract_frames(...)*. It imports *matplotlib* libraries on lines 62, 63

    import matplotlib.pyplot as plt
    import matplotlib.patches as patches

The next time this function uses *matplotlib* is on the line 91, where it closes all plots:

    plt.close("all")

The only other use of *matplotlib* in this file is to (sometimes) create a new plot (lines 104-111)

I have a problem with line 91. When using *DeepLabCut* as a library within another script that also uses *matplotlib*, this line attempts to close my already opened plots, which I don't want it to do. Do you think it is possible to remove this line, or edit it in a way that it only closes the plots that have been created by DLC (if any). I do not understand why is it necessary for this function to programmatically close any plots before creating a new one.

**Comment by MMathisLab** [comment]
this is because if the user is using the cropping features, it opens an image to show them the cropping bound. If the plots are not closed, then this will just plot over the existing plot (if any), which we don't want (i.e. see https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/frame_extraction.py#L104) . If you want to disable this, you can of course just place a `#` in front of line 91 in your local copy of DLC. To find this, you can use `deeplabcut.__file__` to find the location where the package is installed, and edit your version only. hope that helps.

**Comment by aleksejs-fomins** [comment]
Every time `plt.subplots()` is called, a new figure is created. Here is a minimal example to demonstrate that overwriting does not happen.

```
import numpy as np
import matplotlib.pyplot as plt

fig,ax = plt.subplots(1)
ax.plot(np.linspace(0,1,100), np.linspace(0,1,100)**2)

fig,ax = plt.subplots(1)
ax.plot(np.linspace(0,1,100), np.sqrt(np.linspace(0,1,100)))
plt.show()
```
The proposed solution of automatically commenting out code is a hack that I would like to avoid. The problem is that you will in later releases update the source code, and this trick will break down, and will then be a nightmare to find. In the meantime I will comment out the line in my local copy, but I would appreciate a rigorous solution to this problem eventually

I would also appreciate if you would not close issues before there is at least some consensus that the issue has been resolved. I appreciate your work and I would really like to contribute to to DLC. But currently it proves to be quite challenging.

**Comment by AlexEMG** [comment]
Will look into this. Happy to hear your ideas. I guess given that in this step one expects human interaction, one does not need to close all plots, because the human is supposed to close the plot manually. So I removed the ```plt.close('all')``` line. Will be changed in next push. 

https://github.com/AlexEMG/DeepLabCut/commit/4d5d410cad05d6317d83f3873ca3e038589048b9
