### ISSUE TITLE
Error training and analyzing different video file types

### ISSUE THREAD

**Issue by Siolaw** [DeepLabCut/DeepLabCut#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I originally trained the network I'm using with .mp4 videos which works great. However, when I use this same network to analyze .mov videos the tracking is inaccurate. I tried converting the .mov file to .mp4 and there was no difference. 

### Operating System

operating system - Images were extracted and labeled on PC. Dataset creation and video analysis done using Google Colab Pro

### DeepLabCut version

dlc version 2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
The movie file type has zero effect (as your conversion proves) on tracking. All movies are loaded into data as images, regardless of file type.

Just a guess, but chances are your movs simply look different than your original data (different camera? different zoom level? other colors?). Add the troublesome movies to your training dataset and re train so that your model can learn what it's looking for.

**Comment by Siolaw** [comment]
Thanks for your comment. Nope, same camera, same material, just one video downloaded as mov and the other mp4

**Comment by backyardbiomech** [comment]
Training on a single video rarely leads to a well generalizing model even if the other videos are of the same individual animal, due to slight variations in behavior and appearance (e.g. lighting). Your model likely needs a more variable training dataset and more training.  How many images was it trained on? What were your rmse after evaluation?

**Comment by MMathisLab** [comment]
agree with @backyardbiomech -- you will have to give us more information on how it's failing; what do you mean " the tracking is inaccurate." thanks!

**Comment by Siolaw** [comment]
Yup and apologies, you’re correct, found an error on my end. Even though the videos were taken under the same conditions something happened during download that changed the resolution between the two. The original network is on videos of 720p and the ones I have an error on, ie p<.2 for the majority of points tracked, is 1080p. Thanks for your help.

**Comment by Siolaw** [comment]
Endless thank yous for DLC by the way! It’s letting us movement people capture and quantify what we see. A real gift indeed!

**Comment by MMathisLab** [comment]
thanks for the kind words, @Siolaw -- appreciated!!
