### ISSUE TITLE
Quality of Life Wish List in Labelling UI

### ISSUE THREAD

**Issue by A-Telfer** [DeepLabCut/DeepLabCut#1588]
**Is your feature request related to a problem? Please describe.**
Wish List of Quality of Life improvements to the Labelling UI

**Describe the solution you'd like**
Wishlist (expected quality of life improvement measured in ❤️s)
- Display the video name with the image name at the top of UI. [❤️❤️❤️]
- Easier ways to switch between videos (eg. pageup/down loads next/previous video in folder sorted by name) [❤️❤️❤️]
- Check labels should create a single summary folder (perhaps with symbolic links) [❤️❤️]
- Save, Quit, and Open Behavior (eg. ctrl+s, ctrl+q, ctrl+o) [❤️❤️]
- Jump to next unlabeled frame (eg. shift+arrows) [❤️]
- Fix label-deletion. After deleting a label GUI doesn't update immediately and gives an error when trying to create a new label for that bodypart. [❤️]

**Describe alternatives you've considered**
Currently some of these UI interactions feel slower than actually labelling the images. 

eg clicking the UI buttons to switch between videos when labelling many videos (save->quit->yes->select video->open). Having a next video button (perhaps by sorting parent folder and finding index of current video) also removes the navigation difficulty of finding new unlabeled frames. I often keep a text editor open to record the videos I've labeled, I'm sure some others have used similar approaches.

**Additional context**
Willing to help implement

**Comment by MMathisLab** [comment]
HI @A-Telfer have you checked out the new GUI, which we are migrating too? 

https://github.com/DeepLabCut/napari-DeepLabCut

>> Display the video name with the image name at the top of UI. [❤️❤️❤️]

also, any pref for why at the bottom as it is now is not ideal?

Btw, this is on purpose: 

>> Fix label-deletion. After deleting a label GUI doesn't update immediately and gives an error when trying to create a new label for that bodypart. [❤️]

as, if you want to put it somewhere else, drag it! :). If you want to delete it, great, but then not available until the next frame is loaded (prv/next), so that does not need a fix

**Comment by A-Telfer** [comment]
The new UI sounds promising! I'll give it a try today.

> also, any pref for why at the bottom as it is now is not ideal?

Currently when you hit save it replaces the video name. In terms of workflow usually I label all of the frames, instinctively hit save, and then try to figure out what the next video I should load is. By then the video name is gone and I have to use another cue. 

My brain just seems to have memorized that workflow from other applications, but maybe also because I've forgotten to save before in DLC and that can suck. Besides that, it's nice to have important information in a focused area of the screen so I'm not looking around too much. There's definitely some eye strain when you have to move your eyes between corners/sides a lot (another reason hotkeys are great - less looking for buttons when you're doing 200+ frames over 40+ videos).

> if you want to put it somewhere else, drag it! :)

I was going to mention the drag behavior isn't very responsive, but that seemed difficult to fix (figured it was a limitation of the current UI framework). When I try to drag a bodypart I have to sort of coax it in circles around where I want it to go. It's hard to get it to the exact spot I want so often I just delete the label, go to the next image, go back, then readd it. This isn't very important though as mislabeling is rare.

**Comment by anmabu** [comment]
Hey there! 
Maybe a bit off-topic, but still an improvent in quality of life ;) 
Would it be possible to label frames directly when manually selecting them? 
When animals interact closely and you want to pick frames in which they do, it would be a great deal easier to label the frames right then. Even if the animals have individual markers (and even worse when they don't) it's sometimes difficult to tell them or their limbs apart. Having the context of the video helps immensly. 

Exciting news about your napari plug-in! If you ever figure out how to change the default key settings in napari, let me know ;) (A person, who thought Ctrl+Alt+P would be the perfect key combination to play/pause a video developed napari.)

**Comment by A-Telfer** [comment]
I've definitely come across that situation myself. Especially low quality videos it's hard to tell what body part is what without opening the video in a second window and guesstimating the time based on the frame number. I imagine it'll be tricky to implement though

**Comment by MMathisLab** [comment]
Yeah @anmabu! actually that is part a motivation for another GUI we are dev where you can use the video for human-confidence; it might be a while until done/public, but agree would be great :)

**Comment by anmabu** [comment]
Ohh and is there a way to display an error message (Windows 10) without playing a sound as well? 
Trying to set a label which already exists causes a pop-up with an error message and also plays a sound. I get that it's an error message and it's supposed to get your attention but it's annoying to hear the sound. Also, the error can only occur while labeling manually so your attention is already there! 
I usually listen to music or an audiobook while labeling and it's quite disruptive. :upside_down_face:

**Comment by MMathisLab** [comment]
hey @anmabu I had no idea there was a sound! I don't remember get that on my windows machine, but alas I have not tried on windows in a few years maybe ...

**Comment by diegosancarmen** [comment]
Hello DLC Lab!

When I use the DLC GUI to add new videos to an already existing project, if I accidentally click on the wrong video I'm not able to remove it from the list of videos to add. I think it would be really helpful to have the ability to remove videos before uploading, like in a checkbox format.

Also, when I want to extract frames from this new video to add to the project, the program runs through an extraction of the entire folder of videos, including the ones that have already been extracted from and labeled on. In my opinion it would be better if the GUI had an option to "extract from all" or "extract from new videos" etc. Otherwise I have to exit GUI and use ipython to extract frames from the single new video added.

--- edit ---

Additionally, I would like to know if it is possible/logical if, during the `refine_labels()` stage, I could not only refine the existing machine placed labels, but also add labels which aren't already there?  

For example: attached photo shows that the label on the right side says `rightpaw`.  It should really be `rightknee`.  I was wondering... is it possible to have the GUI allow me to add that new label while removing the incorrect one?

![Screenshot (12)](https://user-images.githubusercontent.com/101142209/173696896-7ad2bff7-3b24-4888-b93a-615c390ecce2.png)

**Comment by jeylau** [comment]
Our napari-deeplabcut plugin is now live at https://github.com/DeepLabCut/napari-deeplabcut (and can be installed with `pip install napari-deeplabcut`. Since it will eventually replace the current labeling/refinement GUI, I've ported the missing functionalities in the wishlist there https://github.com/DeepLabCut/napari-deeplabcut/issues. It should already improve your quality of life by a lot compared to the previous GUI 😄 I'll close the issue, but you are welcome to keep discussing the labeling workflow over at the other repo.
