### ISSUE TITLE
Failed to run more than a handful of videos while tracking

### ISSUE THREAD

**Issue by anagigoncalves** [DeepLabCut/DeepLabCut#1666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, 
I've been using deeplabcut for some time now (version 2.1.8.2 on a nvidia geforce rtx 2080). We have now acquired a nvidia geforce rtx 3070 and I've installed the new version (2.2.0.5) with cuda 11.2, tensorflow 2.7 and cudnn 8.2. 
I've also converted the old projects to this new version and everything seems to work fine but, it doesn't track more than 3-4 videos because the kernel suddenly dies without any error. I've tried running in a jupyter notebook, terminal and spyder, all with the same output. I imagine in google colab this won't happen because it seems a GPU problem but I can't seem to fix it.
Any ideas?

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.0.5

### DeepLabCut mode

single animal

### Device type

gpu nvidia rtx 3070

### Relevant log output

```shell
This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-03 13:20:30.044700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5468 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:21:00.0, compute capability: 8.6
2022-02-03 13:20:35.196889: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8200
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@anagigoncalves seems perhaps the memory is not releasing, can you look at the GPU usage: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut & https://deeplabcut.github.io/DeepLabCut/docs/recipes/nn.html?highlight=gpu#limiting-a-gpu-s-memory-consumption

Please post back, but I will close since not a code issue / above should help resolve.

**Comment by anagigoncalves** [comment]
![gpu_usage1](https://user-images.githubusercontent.com/85490532/152795378-38e83d1b-22c1-4376-a624-a84d677f8ae3.jpg)

![gpu_usage2](https://user-images.githubusercontent.com/85490532/152795479-e8e08935-6ffb-47c0-ba77-35b5bb9462a3.jpg)

The memory is releasing. I've tried  
`conda install -c conda-forge cudnn`
which I don't think I did when installing and the process still stops after a few videos.

Let me know if you have other suggestions

**Comment by MMathisLab** [comment]
Hey thanks; I'm not sure ... maybe @backyardbiomech has some ideas; otherwise, I would make arun.py script, something like: https://github.com/DeepLabCut/DLCutils/blob/master/SCALE_YOUR_ANALYSIS/scale_analysis_oversubfolders.py where you could group over videos?

(also, a lot of the GPU is being used; I would try to close all other processes aside from python.dlc

**Comment by backyardbiomech** [comment]
I've never had this problem on my Windows set up.  But your GPU is maxed out - you can see that it is having to access shared GPU memory (using RAM as GPU memory). 
You have only 8GB GPU memory, and it looks like that's the only GPU in the machine so some gets used for other apps and functions (DLC is getting only 5.4 GB). Try quitting everything except DLC, even closing background processes if possible.
Then make sure `batchsize` in `config.yaml` or in your call to analyze videos is 1. 
The kernel crash may be some kind of memory management problem that's not necessarily connected to the GPU installation.

Other than shifting to shared GPU memory, I don't see any indication that the GPU is leading to the original problem, so some other thoughts, none of which should cause a kernel crash, but are worth checking out:

Is there any indication it's a specific video file that causes the problems? Does it always stop on the same video? 
What resolution are your videos? Are they all the same resolution? Can you get it to analyze that video if that's the only one you pass to `analyze_videos`? If you remove that video from the folder will it continue?

Make sure you don't have analysis outputs for the videos (since DLC will not re-analyze videos).

**Comment by anagigoncalves** [comment]
`batchsize` set to 1 worked - thanks a lot! 

I had completely forgot about it as we trained and analyzed videos on the old GPU always with `batchsize` 8 without any problems.

Thank you for all the support, this issue actually made me realize the kind of GPU we have and how we can improve our whole tracking system.
