### ISSUE TITLE
How to quantitatively analyze the CSV files analyzed by deeplabcut?

### ISSUE THREAD

**Issue by BioWalking** [DeepLabCut/DeepLabCut#1706]
Hi,all,I am a newbie and began to use deeplabcut to track the behavior(Single-Pellet Reaching) of mouse. With the help of DLC, I got 4 figures. There is a graph named "trajectory", which seems to have some inter group trends. In order to make my paper more convincing,  I want to quantitatively analyze this behavior or paw trajectory. Is there any good way to achieve it?

**Comment by MMathisLab** [comment]
hi @sudawq welcome to the community - we ask user questions go to the forum: https://forum.image.sc/tag/deeplabcut and are not repeated on GitHub, which we ask is reserved for code issues and therefore has the templates we ask you follow. I will respond to you on the forum, since you posted there too: https://forum.image.sc/t/how-to-quantitatively-analyze-the-csv-files-analyzed-by-deeplabcut/63852
