### ISSUE TITLE
tflite

### ISSUE THREAD

**Issue by ramonhollands** [DeepLabCut/DeepLabCut#1745]
Hi,

Anyone tried to export and use a tflite (tensorflow lite) model? Or are there plans on such a feature?

Best regards,
Ramon

**Comment by ramonhollands** [comment]
Hi,

I just found https://github.com/DeepLabCut/DeepLabCut-live/blob/4ac659accc020b61e7ff85e8029b5f30cf9fbb98/dlclive/dlclive.py#L260

Looks exactly what I need. Happy to check that out tomorrow.

Best regards,
Ramon

**Comment by jeylau** [comment]
I'll close the issue, but feel free to reopen it (or ask for tips at https://forum.image.sc/tag/deeplabcut) if you need help ☺️.

**Comment by eanemo** [comment]
Hi, I have try to export the model to tflite by using the code that appears in the [repo](https://github.com/DeepLabCut/DeepLabCut-live/blob/4ac659accc020b61e7ff85e8029b5f30cf9fbb98/dlclive/dlclive.py#L280). However I have obtain the error about the custom ops:
```
W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1903] The following operation(s) need TFLite custom op implementation(s):
Custom ops: UnravelIndex
```
The tflite model is generated, but the inference process fails due to the custom ops:
`RuntimeError: Encountered unresolved custom op: UnravelIndex.`

Any idea of the solution to this problem? Is possible to export a trained model in tflite or ONNX format?

Thanks a lot for your help.
