### ISSUE TITLE
calculate the mAP on each output video

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1783]
hello, I want to calculate the oks mAP on each output video.  I use "parse_ground_truth_data_file(h5_file)"function to convert my annotated data ( CollectedData.h5) into assemblies. However, the result is like this:
![image](https://user-images.githubusercontent.com/47680845/163919732-a5432324-c769-4d14-9b5d-b35e50b72dbf.png)

Also, after the conversion, what should I send into the evaluate_assembly() function?

_Originally posted by @Jason66661010 in https://github.com/DeepLabCut/DeepLabCut/issues/1710#issuecomment-1101992967_

**Comment by jeylau** [comment]
Hey @Jason66661010, this error was fixed with bd2ff3b2a3ad9f302e4b2b011b5c03b0e96b9777; if you update DLC it will be gone.
As to calculating mAP on each output video, you do need to make sure that you have annotated every single frame yourself; in short, you need DLC (predicted) h5 data file and the corresponding ground truth h5 file.
You pass each one to `parse_ground_truth_data_file` as you rightly do, which will give you two dictionaries (predictions & GT) of animal assemblies keyed by frame index. Then you can simply call the following:
```python
metrics = evaluate_assembly(pred_dict, gt_dict)
print(metrics["mAP"])
```
Note that more arguments are available to `evaluate_assembly`; e.g., in case you want a OKS threshold different from the default one.
