### ISSUE TITLE
Memory leak in `convert_detections2tracklets` or in `stitch_tracklets`

### ISSUE THREAD

**Issue by auesro** [DeepLabCut/DeepLabCut#1804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When we (@isabelperezf) are running `analyze_video` with video files longer than 1 hour (frame size 164 x 180 pixels, 30 fps) in COLAB, the RAM memory rapidly gets used until the environment restarts by itself when it rans out of memory.

This sounds similar to #1468, however the proposed solution with `use_shelve=True` did not make any change.

### Operating System

Windows 10 COLAB

### DeepLabCut version

2.2.1

### DeepLabCut mode

multi animal

### Device type

COLAB GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @auesro please put the output of version in the issue; for long term records of issues "latest" isn't great for us :). Does this happen outside of COLAB? Can you tell me more about your COLAB env, do you have a pro account that doesn't have the low RAM cap?

**Comment by auesro** [comment]
Hi @MMathisLab 
Sorry, I just added the DLC version. It is actually the one COLAB currently uses (2.2.1).
I did not test outside COLAB, for the lack of a proper GPU. However, it started happening recently (last week) since I have been analyzing videos before without this issue.

**Comment by jeylau** [comment]
Hi @auesro, I've run a video analysis for multiple hours on COLAB (the free version) with `use_shelve=True` and have had stable system & GPU RAM usage all along; RAM usage does increase slowly if not using shelve though. I'm not sure about what may be happening in your case. 😕

**Comment by auesro** [comment]
Hi @jeylau , I just ran both with use_shelve=False and True. Attached you can see the progression of RAM use. I took the screenshot a couple of seconds before the runtime restarts by itself when it runs out of memory:
`use_shelve=False`:
![Screenshot from 2022-05-03 14-21-36_shelveFalse](https://user-images.githubusercontent.com/24290290/166453871-f0bc3b49-c762-4e2b-a802-7cf9abb7cdcc.png)

`use_shelve=True`:
![Screenshot from 2022-05-03 14-31-49_shelveTrue](https://user-images.githubusercontent.com/24290290/166453922-e5b20d17-efbe-44b2-bee2-c4ff141767a1.png)

I am happy to share with you the model, mp4 and h5 files if you might consider it useful.

Thanks!

**Comment by MMathisLab** [comment]
does this happen with `robust_nframes=False`? and do you need this to be set to true otherwise?

**Comment by auesro** [comment]
It does. Actually, those videos are already analyzed (as you can read in the cell output) but with auto_track=False. Now we just want to get the tracks (remember our previous issue #1789 ), hence I believe the problem is either in `convert_detections2tracklets` or in `stitch_tracklets`...
`robust_nframes=False` and `use_shelve=True` :
![Screenshot from 2022-05-03 15-06-34](https://user-images.githubusercontent.com/24290290/166459354-786e55e9-44b7-41cf-a3ec-1c4d072e9ecf.png)

**Comment by MMathisLab** [comment]
right, so indeed this is not in analyze_videos at all :) -- so now that makes sense. In short, no memory leak in analyze_videos :) as the videos were analyzed, it's only the `convert_detections2tracklets` and/or in `stitch_tracklets`

**Comment by MMathisLab** [comment]
could you try running each step, convert_detections2tracklets or in stitch_tracklets, separately to profile which seems to be the cause?

**Comment by auesro** [comment]
You are right, I should have phrased the issue correctly, sorry!

**Comment by auesro** [comment]
The issue appears already with `convert_detections2tracklets` :
![Screenshot from 2022-05-03 16-09-56](https://user-images.githubusercontent.com/24290290/166469904-670b524b-4d5c-4c70-b1fd-84536349ce74.png)

**Comment by jeylau** [comment]
@auesro, I came up with a solution in #1820. `use_shelve` will now also affects the behavior of `convert_detections2tracklets`, which should result in very low memory usage! 😃

**Comment by auesro** [comment]
Hi @jeylau, that sounds great. Let me know when its available for COLAB use!
Thanks!

**Comment by jeylau** [comment]
@auesro, right now 😄 In the notebook, just replace `!pip install https://github.com/DeepLabCut/DeepLabCut/archive/master.zip` by `!pip install git+https://github.com/DeepLabCut/DeepLabCut.git@assembler_shelve` and it should install specifically the patch.

**Comment by auesro** [comment]
Testing!

**Comment by auesro** [comment]
Ok. Mixed feelings:
When runnning directly `analyze_videos` with `auto_track=True`, `use_shelve=True` is apparently not passed to `convert_detections2tracklets` and RAM is used as much as before:
![Analyze](https://user-images.githubusercontent.com/24290290/166743920-5470b7a2-6457-4881-8d45-cb0b59fb0fbb.png)
When running `convert_detections2tracklets` RAM is used a lot but, at least with this one video (I have more to test) it did not crash...the downside is the runtime is much longer (processing at ~500it/s vs ~2000it/s):
![Convert](https://user-images.githubusercontent.com/24290290/166744189-edafbb33-6798-4ab8-8a31-c9474147a540.png)

**Comment by jeylau** [comment]
`use_shelve` should be passed to `convert_detections2tracklets` https://github.com/DeepLabCut/DeepLabCut/blob/2f8a87b3fce288c671fd2282fc64506dfcdac4ca/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L629-L640
You must be getting a *_el.pickle alongside the video, could you tell me if it's heavy? Although we're only storing 2D coordinates, I'll take a closer look at this file and tracking in particular.

**Comment by auesro** [comment]
Just to be clear, you mean use_shelve=True should have been passed directly to convert_detections2tracklets from analyze_videos? 

Here are all the files I got for this particular video: 
![Screenshot from 2022-05-04 19-48-27](https://user-images.githubusercontent.com/24290290/166749435-b9205bc8-e8fd-47a8-be61-c6f1c656bb5e.png)

**Comment by QueenKrokuz** [comment]
Hello! Hoping to follow up on this, as I have been using the assembler_shelve branch to analyze lengthy videos. Version information and pickle fix are below. Pickle fix was used because the model was trained on CPU.
![Versions_1](https://user-images.githubusercontent.com/51208433/169705507-62dda0fb-67e7-433f-bc80-3bcecbede23f.jpg)
![Versions_2](https://user-images.githubusercontent.com/51208433/169705505-faab459a-9c08-4d4c-8f86-a240ea692bdd.jpg)
![Versions_3](https://user-images.githubusercontent.com/51208433/169705504-c8c45ff9-e9a3-4046-b724-ab90fbbc54ee.jpg)
![PickleFix](https://user-images.githubusercontent.com/51208433/169705503-41019603-1e4a-4b39-a7e3-b483a76aa110.jpg)


use_shelve = True got my videos through analyze_videos, which outputted four pickle files of approximately equal size for each video. RAM use still steadily increases, but the run does not crash. RAM decreases post-run.
![AnalyzeOutput](https://user-images.githubusercontent.com/51208433/169705451-0cf08be5-d2f9-4605-bbe2-d7517593e667.jpg)

When I run convert_detections2tracklets and stitch_tracklets, the runtime either crashes due to RAM usage or the run completes without file creation. There is an error that seems somewhat unrelated, which I saw when running analyze_videos as well. Previously assumed this error was due to issues finding the next video within the folder, but I have attached it here just in case. Curiously, RAM also stays elevated after the run. If I run another video RAM increases further until the runtime crashes. 

![2%Ram](https://user-images.githubusercontent.com/51208433/169705621-9faef976-d504-483a-a146-0afa7cf6a3ae.jpg) 
![20%Ram](https://user-images.githubusercontent.com/51208433/169705620-00501e2f-82fa-4e30-813c-51d90cce3d48.jpg)
![61%Ram](https://user-images.githubusercontent.com/51208433/169705636-4e512325-8501-4a8b-8f6f-bc49a4c9d697.jpg)
![75%Ram](https://user-images.githubusercontent.com/51208433/169705634-faa666ee-283d-426d-b1c2-45717df33261.jpg)
![96%Ram](https://user-images.githubusercontent.com/51208433/169705640-bdc88e3a-e65c-4bb9-9794-39592a42521e.jpg)
![Error](https://user-images.githubusercontent.com/51208433/169705638-493a2d6e-21ad-444e-b75e-64660d18bc94.jpg)
![PostRunRam](https://user-images.githubusercontent.com/51208433/169705639-3a134e7f-077a-4ace-9d4a-6ceb83759916.jpg)

I did a test to see if the space remaining in my drive storage was a factor. I removed 60% of the video files and doubled my drive storage. No change to RAM increase, elevation, or output. Any thoughts on this?

**Comment by jeylau** [comment]
Hi @QueenKrokuz! Finalizing the assembler_shelve branch still requires some work on my side before it's ready (notably to fix the error your reported and tracklet stitching). I'll also look further at the issue of the RAM not being flushed, thanks for reporting back to me😊

**Comment by QueenKrokuz** [comment]
@jeylau bless you, code genie 🙇 ✨
