### ISSUE TITLE
create_labeled_video_3d got bad results!

### ISSUE THREAD

**Issue by yangyuke001** [DeepLabCut/DeepLabCut#1847]
I followed the introduction :https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html to Visualize my  Videos，2d pose estimate results looks good ,but the 3d results looks strange ，following shown picture is one of video frame :

![5BEE114B-6523-4ed1-A5DC-193BF8B4D310](https://user-images.githubusercontent.com/27425366/170227385-d97c5124-0350-4a19-be3a-32310e193857.png)

Any guidance is appreciated!

**Comment by backyardbiomech** [comment]
If the tracking is accurate, and the frames are synchronized, that looks like a problem with your 3D calibration. My guess is that that your full 3d reconstruction is off (usually due to cameras being too far apart or bad checkerboard detection, or both). 
Either way, it is a camera calibration problem. Check the results of the checkerboard detections and calibrations. 

Since your camera views are so different, the opencv checkerboard detection can have difficulty determining which part of the checkerboard is the origin, and matching them up in both videos.  If you look at the example videos on the page you linked, the 2 views are very similar, and are not rotated. As a general guideline, for two cameras, the cameras should be oriented the same, and the distance between the cameras should be roughly ½ the distance between the cameras and the subject (for a stereo view).

**Comment by yangyuke001** [comment]
@backyardbiomech 
Thank you very much!
I will try it again.

**Comment by MMathisLab** [comment]
@yangyuke001 It doesn't look like your cameras are in stereo config. We have some alternative suggestions (see here: https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html), but I also agree with @backyardbiomech that our 3D code get some 💜, see #1856 . I will close since this was answered, but do come back to this issue is not clear.
