### ISSUE TITLE
OSError: Tracklets are empty.

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1854]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

I've previously run `deeplabcut.analyze_videos()` on these samples and they labeled with acceptable accuracy.  Now when I tried to run the function on the same videos I'm getting the tracklet error.

I used `vid.check_integrity()` as referenced in the @jeylau comment in #982-- the videos aren't corrupt.
I looked through all the github issue tickets related to this problem but none of them address the issue: as aforementioned, the videos are in working condition.

### Operating System

Google Colab

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

Google Colab Pro GPU

### Steps To Reproduce

```
deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType, save_as_csv = True)
```

### Relevant log output

```shell
Using snapshot-20000 for model /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/dlc-models/iteration-0/Trial9May23-trainset95shuffle1
Activating extracting of PAFs
Analyzing all the videos in the directory...
Starting to analyze %  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4
Loading  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4
Duration of video [s]:  30.27 , recorded with  30.0 fps!
Overall # of frames:  908  found with (before cropping) frame dimensions:  1920 1080
Starting to extract posture from the video(s) with batchsize: 8
100%|██████████| 908/908 [01:35<00:00,  9.52it/s]
Video Analyzed. Saving results in /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos...
Using snapshot-20000 for model /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/dlc-models/iteration-0/Trial9May23-trainset95shuffle1
Processing...  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4
Analyzing /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_TrimDLC_resnet50_Trial9May23shuffle1_20000.h5
100%|██████████| 908/908 [00:01<00:00, 678.29it/s]
908it [00:00, 133934.52it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-22-00093eb97f4f>](https://localhost:8080/#) in <module>()
----> 1 deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType, save_as_csv = True)

4 frames
[/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py](https://localhost:8080/#) in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino)
    587                         destfolder=destfolder,
    588                         n_tracks=n_tracks,
--> 589                         modelprefix=modelprefix,
    590                     )
    591         else:

[/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/stitch.py](https://localhost:8080/#) in stitch_tracklets(config_path, videos, videotype, shuffle, trainingsetindex, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, destfolder, modelprefix, track_method, output_name, transformer_checkpoint)
   1157         try:
   1158             stitcher = TrackletStitcher.from_pickle(
-> 1159                 pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals
   1160             )
   1161             with_id = any(tracklet.identity != -1 for tracklet in stitcher)

[/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/stitch.py](https://localhost:8080/#) in from_pickle(cls, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals)
    508             tracklets = pickle.load(file)
    509         class_ = cls.from_dict_of_dict(
--> 510             tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    511         )
    512         class_.filename = pickle_file

[/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/stitch.py](https://localhost:8080/#) in from_dict_of_dict(cls, dict_of_dict, n_tracks, min_length, split_tracklets, prestitch_residuals)
    540                 tracklets.append(Tracklet(data, inds))
    541         class_ = cls(
--> 542             tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    543         )
    544         class_.header = header

[/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/stitch.py](https://localhost:8080/#) in __init__(self, tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals)
    460 
    461         if not len(self.tracklets):
--> 462             raise IOError("Tracklets are empty.")
    463 
    464         if prestitch_residuals:

OSError: Tracklets are empty.
```

### Anything else?

I can provide a Google Drive folder with the pertinent files if needed.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @diegosancarmen, I'd encourage you to have a look at the docs [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-point), and what functions could be used to help you/us diagnose what is happening. Getting an empty tracklet file is not a result of corrupted videos, but of very poor tracking (which may come at the root from inaccurate detections).  `deeplabcut.create_video_with_all_detections` would help you determine whether model detections look pretty. Then bear in mind that when using `analyze_videos` with the default `auto_track=True`, DeepLabCut uses settings that were found to work well across projects, but yours may be different.
When you say that you've previously had it working, was it with a different DLC version?

**Comment by diegosancarmen** [comment]
> When you say that you've previously had it working, was it with a different DLC version?

It was the same DLC version (2.2.1) on the same Google Colab notebook, with the same videos, just a few days ago (05/27).

Running the below function from the [docs](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-point):
```
scorername = deeplabcut.analyze_videos(config_path,['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')
deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')
```
I get an error message
<details>
<summary>

<code>
OS Error
</code>
</summary>
<code>

Using snapshot-20000 for model /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/dlc-models/iteration-0/Trial9May23-trainset95shuffle1

Activating extracting of PAFs

Analyzing all the videos in the directory...

Starting to analyze %  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4

Video already analyzed! /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_TrimDLC_resnet50_Trial9May23shuffle1_20000.h5

Using snapshot-20000 for model /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/dlc-models/iteration-0/Trial9May23-trainset95shuffle1

Processing...  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4

Tracklets already computed /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_TrimDLC_resnet50_Trial9May23shuffle1_20000_el.pickle

Set overwrite = True to overwrite.

The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.

Processing...  /content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSF_TrimA_Trim.mp4

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-10-c81e634196e2>](https://localhost:8080/#) in <module>()

----> 1 scorername = deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='.mp4')
      2 deeplabcut.create_video_with_all_detections(path_config_file, videofile_path, videotype='.mp4')

<<<4 frames>>>

[/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/stitch.py](https://localhost:8080/#) in __init__(self, tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals)
    460 
    461         if not len(self.tracklets):
--> 462             raise IOError("Tracklets are empty.")
    463 
    464         if prestitch_residuals:

OSError: Tracklets are empty.

</code>
</details>

... So I'm not really able to run either `deeplabcut.analyze_videos()` or `deeplabcut.create_video_with_all_detections()`

Upon using `deeplabcut.utils.plot_edge_affinity_distributions()` with the pickle file from the evaluation results, I got the attached plot of histograms.  I'm not sure how to interpret it.  Also attached are the values from the `Combined_Evaluation-results.csv` file.
<details>
<summary>
Attached Files
</summary>
<img
src = "https://user-images.githubusercontent.com/101142209/171456870-b37f6233-dca4-40a1-9e1a-d9260e644ece.png" alt = "cost_dist">

(the image seems to be using a transparent background; I ran the image using both dark/light mode and after pasting it here to GitHub it still is hard to view)

|	| Training iterations: | %Training dataset	| Shuffle number |	Train error(px)	| Test error(px)	| p-cutoff used	| Train error with p-cutoff	| Test error with p-cutoff |
|--- | --- | --- | --- | --- | --- | --- | --- | --- |
|0	| 20000| 	95	| 1	| 2.59	| 3.88	| 0.3	| 2.59	| 3.88|

</details>

> Then bear in mind that when using analyze_videos with the default auto_track=True, DeepLabCut uses settings that were found to work well across projects, but yours may be different.

I apologize for not mentioning beforehand, this is a single-animal project.

**Comment by jeylau** [comment]
I do not understand: if it is a single-animal project, there is no tracking nor stitching stages, so you would not be getting the error you report. Is it a multi-animal project to track only one individual?
Can you check that alongside your video file you find a _full.pickle file? This should allow you to run `deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')`

**Comment by diegosancarmen** [comment]
Hmm.  Not sure what happened but it seems that I've figured a way to make the program keep running.

If I run `deeplabcut.analyze_videos()` and `deeplabcut.create_video_with_all_detections()` I get multiple errors such as the one below.  After getting stuck on the first video it starts to analyze, DLC does not proceed further.

<details>
<summary>
Error Message
</summary>
<code>

Analyzing all the videos in the directory...

Creating labeled video for  FILE0595_C1_pre-aCSF

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxfun_multianimal.py](https://localhost:8080/#) in LoadFullMultiAnimalData(dataname)
    206     try:
--> 207         with open(data_file, "rb") as handle:
    208             data = pickle.load(handle)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE0595_C1_pre-aCSFDLC_resnet50_Trial9May23shuffle1_20000_full.pickle'

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
5 frames
[/usr/lib/python3.7/dbm/__init__.py](https://localhost:8080/#) in open(file, flag, mode)
     83             mod = _defaultmod
     84         else:
---> 85             raise error[0]("need 'c' or 'n' flag to open new db")
     86     elif result == "":
     87         # db type cannot be determined

error: need 'c' or 'n' flag to open new db

</code>
</details>

However, if I call for the specific `'/fullpath/project/videos/testVideo.mp4'` in each of those functions, the program runs smoothly.  Meaning, I still get the aforementioned tracklet error, but I can move forward and create a labeled video (note: the video did indeed show that the program needs much more training).

I wonder if this is an issue caused by the single-animal nature of this project?  I would not like to have to call for every single full path to each video that I analyze, but that appears to be necessary with the current setup.

In regards to being single-animal, the config file states `multi_animal = True` as per the [video tutorial](https://youtu.be/JDsa8R5J0nQ?t=77) for single animal use.  When I created the project I did change the config template so that there is only one individual; is there anything else I might be missing?

**Comment by diegosancarmen** [comment]
Also, due to the tracker error popping up and stopping the code block from running, neither an h5 or csv file with the tracked coordinates is created. So although I'm able to produce a labeled video, I can't access the coordinates.

When I try to run `deeplabcut.create_labeled_video` on a video file after analysis, it runs the code block without interruption but there is no video produced.  The output, rather, is as follows:

```
Starting to process video: /content/drive/MyDrive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE1077_D194_A2_aMSH_Trim_Consistent_Trim.mp4
Loading /content/drive/MyDrive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE1077_D194_A2_aMSH_Trim_Consistent_Trim.mp4 and data.
No unfiltered data file found in /content/drive/MyDrive/DeepLabCut/Trial9B-JDC-2022-05-23/videos for video FILE1077_D194_A2_aMSH_Trim_Consistent_Trim and scorer DLC_resnet50_Trial9May23shuffle1_20000 and ellipse tracker.
```

**Comment by jeylau** [comment]
To be honest, I'd have probably started with a single-animal DeepLabCut project: the workflow is simpler, and it's unclear whether you'll benefit from the specificity of multi-animal processing.
That being said, I am really confused: how could you create a labeled video if DeepLabCut previously indicated that no tracklets were found. Do you mean `deeplabcut.create_labeled_video` or `deeplabcut.create_video_with_all_detections()`? If the video shows that you need to train your model longer, this should be your first concern: the docs do say clearly that it is vital that detections look good before moving forward.
Specific to the tracklet error though, make sure `topktoretain: 1` in the dlc-models/test/inference_cfg.yaml config file.

**Comment by diegosancarmen** [comment]
Could you clarify what you mean by starting with a single-animal DLC project?  I followed the tutorial in the [video](https://youtu.be/JDsa8R5J0nQ?t=77) I linked above.  Is that then not the correct protocol?

I've also been using [this](https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb) Google Colab notebook.

**Comment by diegosancarmen** [comment]
> That being said, I am really confused: how could you create a labeled video if DeepLabCut previously indicated that no tracklets were found. Do you mean `deeplabcut.create_labeled_video` or `deeplabcut.create_video_with_all_detections()`? If the video shows that you need to train your model longer, this should be your first concern: the docs do say clearly that it is vital that detections look good before moving forward.

... What I meant to say is that the code block for `deeplabcut.create_labeled_video` ran but did **not** create a labeled video, and it instead returned that aforementioned output.  
`deeplabcut.create_video_with_all_detections()` worked properly.

**Comment by diegosancarmen** [comment]
> Specific to the tracklet error though, make sure topktoretain: 1 in the dlc-models/test/inference_cfg.yaml config file.

@jeylau This worked perfectly!  Everything's running exactly as it should be now.  Thank you **so** much 😃 
I feel like the `topktoretain: 1` change in the inference_cfg.yaml file should be emphasized in the docs somewhere?

**Comment by vivekhsridhar** [comment]
Hi,

I have the same problem when running my inference. The evaluation seems to work perfectly. I have low errors and the images look great when I say plotting=True. But I'm unable to run inference on any other videos. I've pasted the error below:

`OSError                                   Traceback (most recent call last)
/tmp/ipykernel_84538/2205046491.py in <module>
----> 1 scorername = deeplabcut.analyze_videos(config_path, 
      2                                        ['/media/vsridhar/T7/Work/Data/BlackbuckAnnotations/registration_annotations/downsampled/20230309_SM_Lek1_P2D4_DJI_0782.MP4'],
      3                                        destfolder='/home/vsridhar/DATA/DeepLabCut/projects/02_TerritoryDetectionTest-Vivek-2023-06-30/output/')

~/.local/lib/python3.10/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, in_random_order, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino)
    649                         identity_only=identity_only,
    650                     )
--> 651                     stitch_tracklets(
    652                         config,
    653                         [video],

~/.local/lib/python3.10/site-packages/deeplabcut/refine_training_dataset/stitch.py in stitch_tracklets(config_path, videos, videotype, shuffle, trainingsetindex, n_tracks, min_length, split_tracklets, prestitch_residuals, max_gap, weight_func, destfolder, modelprefix, track_method, output_name, transformer_checkpoint, save_as_csv)
   1187         pickle_file = dataname.split(".h5")[0] + f"{method}.pickle"
   1188         try:
-> 1189             stitcher = TrackletStitcher.from_pickle(
   1190                 pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals
   1191             )

~/.local/lib/python3.10/site-packages/deeplabcut/refine_training_dataset/stitch.py in from_pickle(cls, pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals)
    520         with open(pickle_file, "rb") as file:
    521             tracklets = pickle.load(file)
--> 522         class_ = cls.from_dict_of_dict(
    523             tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    524         )

~/.local/lib/python3.10/site-packages/deeplabcut/refine_training_dataset/stitch.py in from_dict_of_dict(cls, dict_of_dict, n_tracks, min_length, split_tracklets, prestitch_residuals)
    555             else:
    556                 tracklets.append(Tracklet(data, inds))
--> 557         class_ = cls(
    558             tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
    559         )

~/.local/lib/python3.10/site-packages/deeplabcut/refine_training_dataset/stitch.py in __init__(self, tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals)
    473 
    474         if not len(self.tracklets):
--> 475             raise IOError("Tracklets are empty.")
    476 
    477         if prestitch_residuals:

OSError: Tracklets are empty.`

I've also tried some of the suggestions above. The first thing I tried was 
`deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')`

But it gives me the following error
`Creating labeled video for  20230308_SE_Lek1_P2D4_DJI_0766

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/.local/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py in LoadFullMultiAnimalData(dataname)
    216     try:
--> 217         with open(data_file, "rb") as handle:
    218             data = pickle.load(handle)

FileNotFoundError: [Errno 2] No such file or directory: '/home/vsridhar/DATA/DeepLabCut/projects/02_TerritoryDetectionTest-Vivek-2023-06-30/videos/20230308_SE_Lek1_P2D4_DJI_0766DLC_dlcrnetms5_02_TerritoryDetectionTestJun30shuffle1_30000_full.pickle'

During handling of the above exception, another exception occurred:

error                                     Traceback (most recent call last)
/tmp/ipykernel_84538/436182917.py in <module>
----> 1 deeplabcut.create_video_with_all_detections(config_path, 
      2                                             ['/home/vsridhar/DATA/DeepLabCut/projects/02_TerritoryDetectionTest-Vivek-2023-06-30/videos/20230308_SE_Lek1_P2D4_DJI_0766.MP4'])

~/.local/lib/python3.10/site-packages/deeplabcut/utils/make_labeled_video.py in create_video_with_all_detections(config, videos, videotype, shuffle, trainingsetindex, displayedbodyparts, destfolder, modelprefix)
   1049             print("Creating labeled video for ", str(Path(video).stem))
   1050             h5file = full_pickle.replace("_full.pickle", ".h5")
-> 1051             data, _ = auxfun_multianimal.LoadFullMultiAnimalData(h5file)
   1052             data = dict(
   1053                 data

~/.local/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py in LoadFullMultiAnimalData(dataname)
    218             data = pickle.load(handle)
    219     except (pickle.UnpicklingError, FileNotFoundError):
--> 220         data = shelve.open(data_file, flag="r")
    221     with open(data_file.replace("_full.", "_meta."), "rb") as handle:
    222         metadata = pickle.load(handle)

/usr/lib/python3.10/shelve.py in open(filename, flag, protocol, writeback)
    241     """
    242 
--> 243     return DbfilenameShelf(filename, flag, protocol, writeback)

/usr/lib/python3.10/shelve.py in __init__(self, filename, flag, protocol, writeback)
    225     def __init__(self, filename, flag='c', protocol=None, writeback=False):
    226         import dbm
--> 227         Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
    228 
    229 

/usr/lib/python3.10/dbm/__init__.py in open(file, flag, mode)
     83             mod = _defaultmod
     84         else:
---> 85             raise error[0]("db file doesn't exist; "
     86                            "use 'c' or 'n' flag to create a new db")
     87     elif result == "":

error: db file doesn't exist; use 'c' or 'n' flag to create a new db`

I also tried going to the inference_cfg.yaml file and changing the `topktoretain: 1` and that didn't change the error either. I would appreciate any help with being able to run my inference, especially because the evaluation results look beautiful!! :D

Thanks and cheers!
Vivek
