### ISSUE TITLE
bug in label_frames with the lable positioning

### ISSUE THREAD

**Issue by netta-hub** [DeepLabCut/DeepLabCut#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hi :)

in the label_frames part when i right click on the mouse the label appeared not where i positioned it. when i left clicked on the mouse I couldn't catch the label and make it move. when I finally managed to "catch" it not by clicking on the actual label, it moved to the opposite direction than the one I was dragging it to.
when i tried to delete with middle click it also didn't work.

can someone help me with this one?

thanx in advance! 

### Operating System

operating system windows 10

### DeepLabCut version

dlc version 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu not relevant

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
can you record a video? I can't reproduce this behavior.

**Comment by netta-hub** [comment]
https://user-images.githubusercontent.com/107629837/174472725-42a3af89-7fbc-4be2-b814-c55d00f7b963.mov

**Comment by jeylau** [comment]
Hi @netta-hub! The GUI looks flipped (i.e., all elements appear as if they were aligned right): is this due to recording or because of your language settings (like hebrew maybe)?
For a more modern feel and a smoother labeling experience though, I'd encourage you to look at our new labeling plugin: https://github.com/DeepLabCut/napari-deeplabcut
It's easy to install, and meant to slowly replace the current labeling GUI. It should work well in your case. ☺️

**Comment by netta-hub** [comment]
thank you!
it seems to work
