### ISSUE TITLE
Labeling Frames and Training the Network in different versions

### ISSUE THREAD

**Issue by KonKob** [DeepLabCut/DeepLabCut#1890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I used DLC version 2.2.1 to label the frames and switched to version 2.1.8.1 to create a training dataset and train the network,  the error ocurred: “TypeError: expected str […] not tuple”.

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.1.8.1
dlc version 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu & cpu

### Steps To Reproduce

I used the standard environment as in the Documentation to create a new DLC project in version 2.2.1 using CPU and labeled the Frames of the video. 
For the training I wanted to switch on a server to use GPU, where the DLC version 2.1.8.1 is installed. 
When I try to create the training dataset there it throws the following error: “TypeError: expected str […] not tuple”
I also checked the .csv files and the ones created in 2.1.8.1 have a different structure than the ones created in 2.2.1 (as also described in this forum: https://forum.image.sc/t/labelling-images-on-different-devices-leads-to-typeerror-expected-str-not-tuple-and-different-csv-content/64109.
Creating a new .h5-file in version 2.2.1 from the .csv-files from version 2.1.8.1 also gave an error. 
Creating the Training dataset in version 2.1.8.1 did work, but using this trainingset in 2.2.1 did not.
I could start the training on the CPU in version 2.1.8.1 without any problems.

### Anything else?

![image](https://user-images.githubusercontent.com/104254966/175567408-f539dca4-8b8a-42ab-9f04-3fc508f36519.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @KonKob, you're right, data indices are structured slightly differently since https://github.com/DeepLabCut/DeepLabCut/pull/1584. To avoid storing image paths with OS-specific path separators, we got rid of those and decided to store them as tuples in a pandas' hierarchical MultiIndex. It makes it much easier to move projects across multiple platforms. To fix it, the simplest way is to have matching DLC versions; an alternative is to programmatically edit the h5 file, doing the following:
```python
import os
import pandas as pd

df = pd.read_hdf('h5path')
df.index = [os.path.join(*row) for row in df.index.to_list()]
df.to_hdf('h5path_new', key='data')
```
It simply loads your h5 data, rebuilds the image paths the old way, and writes the data. I would not recommend it though, as I find it simpler and less brittle to update DeepLabCut.
I hope that helps!

**Comment by KonKob** [comment]
Thank you for your answer!
Unfortunately it is not possible for me to update the DLC version, since I don't have administrator rights.
![image](https://user-images.githubusercontent.com/104254966/176374673-9a67bf8c-8b3e-48c5-8296-71624b7ab16f.png)


Using your suggested code, I got a new h5 file, but when I tried to use it for creating a training dataset, the following error occured:

**Comment by jeylau** [comment]
Aw... Resave your data with the code above but use `df.to_hdf(..., key='df_with_missing')` and you will be fine. 😊

**Comment by KonKob** [comment]
Thank you a lot, now it works!
