### ISSUE TITLE
Videos are upside down

### ISSUE THREAD

**Issue by matthew-levy** [DeepLabCut/DeepLabCut#1935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm using an iPhone camera to start training DLC to detect licks. When I import the video into the DLC GUI, the video and all extracted frames are upside down. Is there anyway to fix this? I've also tried manually flipping the videos on the phone.

### Operating System

Windows10

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by neslihanedes** [comment]
Hi @matthew-levy!

You can use ffmpeg to rotate your videos before extracting-labeling your frames.

`ffmpeg -i yourvideo.mp4 -vf "vflip" yourvideo_rotated.mp4`

Depending on the rotation need, you can change **vlip** as **hflip**.

**Comment by matthew-levy** [comment]
Hi! Thank you for this. I did this and was successfully able to save a flipped video, but when I import that into DLC it is still inverted. Both the regular and flipped videos look the same when extracting&labeling the frames.

**Comment by MMathisLab** [comment]
can you share a screen shot? I can't reproduce this with my iphone videos

**Comment by matthew-levy** [comment]
Here are some screenshots of a normal video, the flipped video, and how they both look in the extract frames GUI. Please let me know if there is anything else you would like to see. 
![normal video](https://user-images.githubusercontent.com/105824413/183474578-2e2b4372-7787-4b7c-8edb-f830aa2a9bc9.png)
![flipped video](https://user-images.githubusercontent.com/105824413/183474582-331997e5-2fff-4d06-aaf8-25762aae352f.png)
![extract frames normal](https://user-images.githubusercontent.com/105824413/183474583-47b5fd11-66a8-42d6-82ff-0446a8555cab.png)
![extract frames flipped](https://user-images.githubusercontent.com/105824413/183474586-5d5d5e9b-a55a-46c4-9c79-4ff75c165b2b.png)

**Comment by jeylau** [comment]
@matthew-levy, is your machine set with a language other than English? It may not be related at all, but it reminded me of #1881.

**Comment by matthew-levy** [comment]
It's set to English... I figured it out but it doesn't make much sense to me. If I run hflip and then vlip on that hflipped video, it saves the video in the original orientation but for some reason imports into DLC in this orientation as well. Thank you for the help!

**Comment by peabody124** [comment]
I ran into a similar issue with videos acquired in portrait mode on an iPad. It's very curious because the frames extracted from the videos are oriented correctly, but the frames in the output video are inverted. I suspect inference is also happening on inverted images too, as the tracking performance is very poor.

deeplabcut 2.2.2
opencv-python version 4.6.0.66 (although a possible issue is whether frames were extracted with a different set of libraries)

I've run into similar issues in my own code when using video acquired on smartphones due to variations in handling of the rotation metadata. I suspect this is the case for these videos. I've attached the results from ffprobe below, which shows that despite being portrait they have metadata indicating they are rotated (bolded). I've seen quirks between libraries where the rotation is handled backward, which can create the inversion like I'm seeing (which isn't addressed with a hflip or vflip, but requires simply reencoding it without any rotation since ffmpeg handles it correctly).

@MMathisLab  TL;DR: does DLC use a different video reader library to extract the files for annotation compared to running inference? If you point me at the difference I can try and offer a PR to handle the metadata more robustly.

> ffprobe "112006_36wk_3 copy.MOV"
ffprobe version 5.1.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with clang version 14.0.6
  configuration: --prefix=/d/bld/ffmpeg_1662055343048/_h_env/Library --cc=clang.exe --cxx=clang++.exe --nm=llvm-nm --ar=llvm-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libfontconfig --enable-libopenh264 --ld=lld-link --target-os=win64 --enable-cross-compile --toolchain=msvc --host-cc=clang.exe --extra-libs=ucrt.lib --extra-libs=vcruntime.lib --extra-libs=oldnames.lib --strip=llvm-strip --disable-stripping --host-extralibs= --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --pkg-config=/d/bld/ffmpeg_1662055343048/_build_env/Library/bin/pkg-config
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '112006_36wk_3 copy.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2022-02-16T17:26:27.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 35.000000
    com.apple.quicktime.location.ISO6709: +41.8965-087.6208+230.399/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPad Pro (10.5-inch)
    com.apple.quicktime.software: 15.2.1
    com.apple.quicktime.creationdate: 2022-02-16T11:26:27-0600
  Duration: 00:01:50.67, start: 0.000000, bitrate: 7815 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 7673 kb/s, 29.99 fps, 29.97 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2022-02-16T17:26:27.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
    Side data:
      **displaymatrix: rotation of -90.00 degrees**
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2022-02-16T17:26:27.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2022-02-16T17:26:27.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2022-02-16T17:26:27.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 34 kb/s (default)
    Metadata:
      creation_time   : 2022-02-16T17:26:27.000000Z
      handler_name    : Core Media Metadata

**Comment by MMathisLab** [comment]
cc @jeylau @AlexEMG - let's check again?

**Comment by jenniferleestma** [comment]
Hey all, was there every any solution determined for this other than using the vertical and horizontal flipping?  We currently have the upside down issue happening on a mac, but not on a windows.  I'm trying to avoid adding in video flipping so we can still operate easily between our involved computers, so just curious if the root of this issue was ever worked out?  Thanks so much for the help!
