### ISSUE TITLE
pose_cfg.yaml crop parameters (Auto-cropping parameters) 

### ISSUE THREAD

**Issue by rnrpereira** [DeepLabCut/DeepLabCut#200]
Using: **Ubuntu 16.04 LTS**, with an Anaconda Env, & **DeepLabCut 2.0.4.1**

I have a question: My **videos are 640x480** and I've used **crop parameters** for frame extraction as follows: [width_min, width_max; height_min, height_max] = [**255, 537; 93, 446**] 

Now, I'm about to **start training** and  I'm editing the `pose_cfg.yaml` file.
I suppose correct setings should be: leftwidth = 255; rightwidth = 537; bottomheight = 446; topheight = 93 as frame origin is 0,0 at top-left corner.

=> However, I'm not sure about what `minsize` means. Is it the width*height? 
From user_guide docs or in the papers it says: "_define dimensions and limits for cropping_"

**Comment by AlexEMG** [comment]
So after frame extraction your frames are ~350 x 280  pixels.

With regard to auto-cropping. Lets for simplicity only consider one direction (because all others are essentially the same). In a given iteration a random body part is picked, then a number is picked uniformly from (minsize, minsize+ rightwidth). Then the image is cropped with this number as an upper, right boundary. 

A few things should be considered:
- if this is larger than the image itself, then there is no **cropping (or padding)** 
- from the body part the cropping will be at least "minsize" away. This makes sure that he cropped parts are not too small (and still contain visual + geometric information about other bodyparts)

Btw:
https://github.com/AlexEMG/DeepLabCut/blob/887814e960ef70d193745c9716c1cf9a871abe33/deeplabcut/pose_estimation_tensorflow/default_config.py

has a description:
```
#Parameters for augmentation with regard to cropping
cfg.crop = False
cfg.cropratio= 0.25 #what is the fraction of training samples with cropping?
cfg.minsize= 100	#what is the minimal frames size for cropping plus/minus ie.. [-100,100]^2 for an arb. joint
cfg.leftwidth= 400		
#limit width  [-leftwidth*u-100,100+u*rightwidth] x [-bottomwith*u-100,100+u*topwidth] where u is always a (different) random number in unit interval
cfg.rightwidth= 400
cfg.topheight= 400
cfg.bottomheight= 400
#these will be updated by trainingsetmanipulation.py in the future
```

This would be perhaps an ideal question for the forum: https://forum.image.sc/tags/deeplabcut

**Comment by rnrpereira** [comment]
Thank you! I got it.
It wasn't clear to me that the _auto-cropping_ was part of data-set augmentation strategy.
For me the two crop terminologies were related to similar tasks.

Sure, I'll post the question at the forum.

**Comment by AlexEMG** [comment]
Great, I hope the answer was helpful!
