### ISSUE TITLE
M1 mac installation issue

### ISSUE THREAD

**Issue by bendichter** [DeepLabCut/DeepLabCut#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've found a few different issues about installation on M1, but haven't found this problem specifically.

```shell
git clone https://github.com/DeepLabCut/DeepLabCut.git
cd DeepLabCut
conda env create -f DEEPLABCUT_M1.yaml
```

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - apple::tensorflow-deps

```

### Operating System

Ventura (13.0)

### DeepLabCut version

latest. I'm unable to import deeplabcut to check the number.

### DeepLabCut mode

single animal

### Device type

M1 mac

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by guiwitz** [comment]
Hey @bendichter

I managed to use this new installation configuration without problem on an M1. My best guess here, is the you are using an older conda (anaconda maybe?) installation that was still configured to use Rosetta in order to emulate os64. You can check this with from your base environment with ```python -c "import platform;print(platform.machine())"```. If it doesn't print arm64 you are using the old version. If that's the case, the problem is then that conda is looking for ```tensorflow-deps``` in the apple channel. But as you can see [here](https://anaconda.org/apple/tensorflow-deps) that package only exists for arm64 and therefore you get the message "package not found". So you have two choices: uninstall your current (ana)conda and install a newer version designed for M1 (arm64). Or leave your current conda in place and install a parallel version. In the latter case, you might run into trouble with where conda is looking for your environments, so it's less clean.

**Comment by bendichter** [comment]
indeed:

```shell
$ python -c "import platform;print(platform.machine())"
x86_64
```

I'll try updating my conda. Thanks for the help!

**Comment by bendichter** [comment]
With the latest version of miniconda fro M1 I am getting:

```shell
$ python -c "import platform;print(platform.machine())"
arm64
```

this is promising...

**Comment by bendichter** [comment]
The install runs and `import deeplabcut` also works. Thanks for the help!

**Comment by jeylau** [comment]
Awesome! Thanks a lot @guiwitz!

**Comment by guiwitz** [comment]
Great, glad I could help!
