### ISSUE TITLE
Refining machinelabels

### ISSUE THREAD

**Issue by OmerBarkai** [DeepLabCut/DeepLabCut#2163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am opening folders that were not manually labeled (i.e containing machinelables data) with Napari to correct (or refine) the labels. This is a step which I understand that can increasing the performance of DLC's automatic labeling(?).

After correcting the mislabeled bodyparts, I press Save selected layers and try to exit Napari. 
Although trying to save the selected layers, Napari opens a dialog box saying "Please save your data before closing" - there is no way to close Napari, and unfortunately it also does not save the changes I made. 

I also tried pressing "Save all layers" but that ends up crashing the DLC GUI. 

### Operating System

Windows

### DeepLabCut version

2.3.0

### DeepLabCut mode

single animal

### Device type

GeForce 3060

### Relevant log output

```shell
lambda: _save_layers_dialog(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_widgets.py", line 94, in _save_layers_dialog
    self.viewer.layers.save("", selected=True, plugin="napari-deeplabcut")
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\components\layerlist.py", line 476, in save
    return save_layers(path, layers, plugin=plugin, _writer=_writer)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\io.py", line 229, in save_layers
    _written, writer_name = _write_single_layer_with_plugins(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\io.py", line 442, in _write_single_layer_with_plugins
    written_paths, writer_name = _npe2.write_layers(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\plugins\_npe2.py", line 101, in write_layers
    paths, writer = io_utils.write_get_writer(
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 115, in write_get_writer
    return _write(path, layer_data, plugin_name=plugin_name, return_writer=True)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\io_utils.py", line 224, in _write
    res = writer.exec(args=args)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\npe2\manifest\utils.py", line 65, in exec
    return self.get_callable(_registry)(*args, **kwargs)
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_writer.py", line 65, in write_hdf
    config = _load_config(os.path.join(project_folder, "config.yaml"))
  File "C:\Users\ch226295\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_reader.py", line 153, in _load_config
    with open(config_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ch226295/Desktop/DLCProjects/PalmReaderBodyFingers-OB-2023-01-25/labeled-data/0_2_body\\config.yaml'
```

### Anything else?

from the output, it seems it is looking for a config.yaml file within the labeled-data video frames folder. I tried to create a "dummy" config.yaml file to see if that help, but it did not unfortunately. 

Also, please let me know if the refinement process I described should increase algorithm performance. 

Thank you so much for your support!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MakeSometh1ngWonderful** [comment]
**Addressing the Error**
Typically, the path to the config file would be: 'C:/Users/ch226295/Desktop/DLCProjects/PalmReaderBodyFingers-OB-2023-01-25/config.yaml'
So, I would start by checking your config_path variable.
**Performance Improvement**
The model will need to be retrained with the refined data in order to increase performance. This process is described [here](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#:~:text=Once%20the%20dataset%20is%20merged%2C%20the%20user%20can%20test%20if%20the%20merging%20process%20was%20successful%20by%20plotting%20all%20the%20labels%20(Step%20E).%20Next%2C%20with%20this%20expanded%20training%20set%20the%20user%20can%20now%20create%20a%20novel%20training%20set%20and%20train%20the%20network%20as%20described%20in%20Steps%20F%20and%20G.).
Roughly, you should execute the following lines:
`deeplabcut.refine_labels(config_path)`
`deeplabcut.merge_datasets(config_path)`
`deeplabcut.create_training_dataset(config_path)`
`deeplabcut.train_network(config_path, shuffle=1, trainingsetindex=0, gputouse=None, max_snapshots_to_keep=5, autotune=False, displayiters=100, saveiters=15000, maxiters=30000, allow_growth=True)`

Hope that helps!

**Comment by HayatoMaeda0405** [comment]
I also have some troubles in this process.
1) I cannot use 'Labeling GUI' button on GUI when I reload the project or trying to use the extracted frames I generated in remote server. Only after 'Extracted frame' button on GUI this button works.

2) In the explained process in Github(link you posted), the extracted frames are supposed to be stored in subdirectory of labeled-data folder. However, after 'Extracted frame' original frames and extracted frames are stored in the same directory. Also I cannot find 'Load labels' button so the process of refine labels is conplicated.

3) I also cannot save the process of refine labels. First of all, 'Save all layers' button does not work and napari is terminated(this problem also happens in label frames). So I used 'Save selected layer(s)' and "data successfully saved" message was shown in the display of napari, but, ater closing napari and reopening the same folder it appears that the data does not saved.

**Comment by jeylau** [comment]
This should have been fixed with napari-deeplabcut==0.1.1 (you can run `pip install -U napari-deeplabcut` to get it). If the error persists, please let me know. Note though that you should only ever saved the Points layer (as explained here https://github.com/DeepLabCut/napari-deeplabcut#save-layers).

**Comment by witeal** [comment]
Hi everyone,

I'm facing exactly the same issue even though I'm using the updated version of napari-deeplabcut. When I try to save the labelling refined from the files machinelabels.csv nothing happens. 

Please let me know If I can try anything else to solve this problem ? 

Thanks by advance.

**Comment by vchiang001** [comment]
Using DLC 2.3.8 I am encountering the same issue. Folders with only machinelabels, when save selected layer does not create CollectedData file. Instead a filenotfound error occurs, to try to find config.yaml in the selected machinelabels folder. 
![image](https://github.com/DeepLabCut/DeepLabCut/assets/72048480/3b5299d3-b330-4796-87fd-d956f72154d7)

**Comment by Piotr-23** [comment]
Hi, I am having a similar issue with DLC 2.3.8 and napari-deeplabcut Version: 0.2.1.3. Following initial training, I analyzed 11 novel videos. As predictions could be better, I refined labels with the "jumps" option: this step created 11 novel folders with 50 PNGs each under labeled-data and every folder has machinelabels.csv and machinelabels-iter0.h5. I then corrected misplaced labels and saved (Ctrl+S). This created CollectedData_piotr.csv and CollectedData_piotr.h5 files. So far so good. 

I then clicked "merge dataset" in GUI, but after creating new Training set (iteration-1), the files are of the same size as iteration-0 and, importantly, the CSVs show the same old number of annotated PNGs (same number of rows). I think, by merging, the new training set should be expanded by 11 videos x 50 frames, yes? Am I doing something wrong?

The folders still have machine labels files, and BTW, the sequence of PNGs in machinelabels.csv and in CollectedData_piotr.csv is different. Please let me know and thanks in advance.

**Comment by Piotr-23** [comment]
OK, to answer myself:

Assume that following initial network training (150,000 iterations of a dyadic rat social behavior with 9 body parts project) gave better results than 200,000), as myself, you analyzed novel 11 videos and now you want to use "Extract Outlier Frames" tab to run the napari plugin for the ultimate goal of improving network's predictions. 

These 11 are the videos that were NOT used for the network training, and logically, the outliers could show some misplaced body parts labels... In my case there were some body parts of individual_1 placed on the body parts of individual_2 (so that individual_2 had the head and nose of individual_1 and sometimes, vice versa). 

In napari, remember to use the "F" button to switch between colored body parts (blue is the head on both rats, green are the noses, etc) into green points of individual_1 and yellow points of individual_1) -- to find that.

After opening napari, you'll see only machine labels layer. That's OK, probably by design if napari is opened from "Extract outlier frames (*)" tab (and not from the "Label frames" tab, which eventually will show both machine's **and** Piotr's layers). 

After correction of mislabeled body parts/frames and saving, in every sub-folder of the "labeled-data" folder, the two new files appear: (in my case):
CollectedData_piotr.h5 and
CollectedData_piotr.csv

However:
Pressing the "Merge datasets" button under "Extract Outlier frames" and then, "Create training set".... does not expand the 
CollectedData_piotr.csv in 
D:\LEWIATAN\dlc_circadian_clean\training-datasets\iteration-1\UnaugmentedDataSet_v5_0_Dec30_ !

as it still has (in my case) the only original 1056 rows.
(the same number of rows as in the:
CollectedData_piotr.csv
under
D:\LEWIATAN\dlc_circadian_clean\training-datasets\iteration-0\UnaugmentedDataSet_v5_0_Dec30_
)

Please mind iteration-0 and iteration-1 -- automatically created sub-folders with increased iteration numbers, following merging!

To overcome this apparent bug, one has to **add** novel (11) videos into the project

Suppose the novel 11 videos exist in the "test_11_novel_videos" folder.
If you open GUI DLC (2.3.8) with python -m deeplabcut
And try to add them, this will not work!

The "novel" (they are not so novel, because they were analyzed by the initial network!) -- videos have to be placed in the ../videos folder, otherwise the trick will not work!

So, first, copy 11 videos from the "test_11_novel_videos" folder into a .../videos folder 
Then add them into the the project (the very left tab of GUI)

And then, merge -> create training dataset (this **will** expand the existing training data set with the novel observations: "corrected" 11 folders x 50 observations in every folder) => train network

Uff. A long but detailed workflow) | P
