### ISSUE TITLE
A way to get the dataframe itself as an output of video analasys

### ISSUE THREAD

**Issue by YoaviA** [DeepLabCut/DeepLabCut#2211]
I am using deeplabcut.analyze_videos() as a part of my code, with a video i have on my git for testing, and as result i need to manually remove the output files each test-run, which is pretty tedious. If i could have a way to get only the DataFrame as the output of this function, it would really help me to debug the code.

**Comment by jeylau** [comment]
As addressed on the [forum](https://forum.image.sc/t/a-way-to-get-the-dataframe-itself-as-an-output-of-video-analasys/80110), you could copy-paste the content of the `AnalyzeVideo` function, but instead of saving data to disk have it return [here](https://github.com/DeepLabCut/DeepLabCut/blob/a61211dea445b664364c5befe5400dcbae9d577d/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L1122):
`df = pd.DataFrame(PredictedData[:nframes, :], columns=pdindex, index=range(nframes))`
