### ISSUE TITLE
Can't plot specific bodypart in GUI

### ISSUE THREAD

**Issue by tokioshima** [DeepLabCut/DeepLabCut#2230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello!

I want to plot only some bodyparts _(like only the nose and the object 1 but not the tail and ears for example)_, so I uncheck "plot all bodyparts" in the "create videos" windows and I chose the bodypart that interests me. But when I run "create videos" after that, it create me a video with all bodyparts ploted and the same problems with graphics in the plot-poses file.

Have you some idea to help me? 
Thank in advance! :)

### Operating System

Windows 10 Pro

### DeepLabCut version

2.3.3

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
thanks for reporting - we will look into it! seems a GUI issue, not in the underlying code. So you can also use the terminal
```
ipython
import deeplabcut
cfg = 'path/totheproject/config.yaml'
deeplabcut.create_labeled_video(cfg, displayedbodyparts=["tail","nose"]
```

To see all options: 
```
deeplabcut.create_labeled_video?

Signature:
deeplabcut.create_labeled_video(
    config,
    videos,
    videotype='',
    shuffle=1,
    trainingsetindex=0,
    filtered=False,
    fastmode=True,
    save_frames=False,
    keypoints_only=False,
    Frames2plot=None,
    displayedbodyparts='all',
    displayedindividuals='all',
    codec='mp4v',
    outputframerate=None,
    destfolder=None,
    draw_skeleton=False,
    trailpoints=0,
    displaycropped=False,
    color_by='bodypart',
    modelprefix='',
    init_weights='',
    track_method='',
    superanimal_name='',
    pcutoff=0.6,
    skeleton=[],
    skeleton_color='white',
    dotsize=8,
    colormap='rainbow',
```

**Comment by KonradDanielewski** [comment]
The logic for checking the box is reversed and it doesn't update the bodyparts. 
This change fixes the plotting to only display selected bodyparts. I can make a pull request with a fix
![image](https://github.com/DeepLabCut/DeepLabCut/assets/54865575/747f56dd-535d-4f96-aee7-b56ee53a5e0e)

Skeleton is drawn for all bodyparts anyway but this is a skeleton drawing issue. I guess I can try and fix it separately but it's little more work since checking for chosen bodyparts has to happen in multiple functions.
