### ISSUE TITLE
Saving layers does not work for deleted labels.

### ISSUE THREAD

**Issue by VistiStenmo** [DeepLabCut/DeepLabCut#2253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When saving selected layer in Napari GUI, it will not save the deletion of a point. It saves the movement of points just fine. 

### Operating System

Windows 11 Pro, 22H2

### DeepLabCut version

2.3.4

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 4090

### Steps To Reproduce

Open GUI.
Go to "extract outlier frames" tab.
Select some videos. 
Click "Labelling GUI" button.
Move desired folder to Napari window. 
Delete a label in the MachineLabels folder
Click "File" -> "Save selected layers"
Close napari
Click "Labelling GUI" in to open Napari again. 
Load up your folder again. 
The label you deleted should be back, instead of being deleted. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @VistiStenmo, thanks for reporting this bug. I'll look at it today, and get back to you.

**Comment by jeylau** [comment]
After testing, I notice that the deleted points from the machinelabels layer are correctly absent in the CollectedData file (which is automatically updated upon saving the data); the machinelabels file is not overwritten though (intentionally), so the points can still be seen in this layer. When reloading the folder in napari, and masking or deleting the machinelabels layer, are deleted points still there or was it just caused by the superposition of the layer?
