### ISSUE TITLE
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 15 and the array at index 1 has size 14

### ISSUE THREAD

**Issue by alsdk6720** [DeepLabCut/DeepLabCut#2280]

**Comment by n-poulsen** [comment]
Hi @alsdk6720, please edit your post to use our required template or close the issue if you manage to resolve your issue by yourself, thanks!

**Comment by demirand4** [comment]
I am facing the same now. It would be nice to know how the issue was solved.

File ~/anaconda3/envs/DLC/lib/python3.8/site-packages/numpy/lib/index_tricks.py:419, in AxisConcatenator.__getitem__(self, key)
    416     for k in scalars:
    417         objs[k] = objs[k].astype(final_dtype)
--> 419 res = self.concatenate(tuple(objs), axis=axis)
    421 if matrix:
    422     oldndim = res.ndim

File <__array_function__ internals>:200, in concatenate(*args, **kwargs)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 20 and the array at index 1 has size 21

I know the error is related to how many body parts we set in the config.yaml file because if I add or remove bodyparts, I can see the size value consistently change in the error. In our case we have 20 bodyparts as labels.
