### ISSUE TITLE
Pose_cfg file not found

### ISSUE THREAD

**Issue by davidSafeloc** [DeepLabCut/DeepLabCut#229]
Win10, CPU, Anaconda (3.6) to create the label data Im running DeepLabCut Version 2.0.5

Creating the network and training in a singularity container which runs on a UNIX machine with 2.0.4.1

I'm running train_network with the config file, but getting an error that the pose_cfg is not in its directory.

I've double checked multiple times, and the pose_cfg file is in right place (I attach the config and the pose_cfg file).

[Files.zip](https://github.com/AlexEMG/DeepLabCut/files/2926867/Files.zip)

I'm at the correct parent directory when running the code, and all previous functions in the process worked.

[Errno 2] No such file or directory: 'Brown_Rats-David-2019-03-01/dlc-models/iteration-0/Brown_RatsMar1-trainset95shuffle1/train/pose_cfg.yaml'

Any idea?

**Comment by MMathisLab** [comment]
So, the error is just that it cannot find it as it's not linked to the config file correctly. The config.yaml file variable ``project path`` must be the FULL path on the UNIX machine; so when you move the whole folder over to the "server," you need to edit just the ``project path`` (not just the project folder ;). 

And, for simplicity, we recommend that you create the training set ON the server, i.e. create_training... must be run locally. (otherwise, as you see in your pose_cfg that the project path is incorrect there too).

**Comment by davidSafeloc** [comment]
Thank you it works now and sorry for the basic question :S.

**Comment by MMathisLab** [comment]
no problem!
