### ISSUE TITLE
Can't label frames

### ISSUE THREAD

**Issue by ocmistr** [DeepLabCut/DeepLabCut#2362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am new to the new version of the DLC GUI and I am having a lot of issues. First I wasn't able to extract frames. I finally figured out that bug, but know I can not load any frames to label. The napari doesnt even open. When I click on a folder that I know has extracted frames in it I get message that says "LoadLibrary with error 87: The parameter is incorrect." 
![image](https://github.com/DeepLabCut/DeepLabCut/assets/143367432/d1842d78-3ece-40b0-bae6-1440b2cf98fb)

and in the cmd line it says "WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=120"
![image](https://github.com/DeepLabCut/DeepLabCut/assets/143367432/2267578b-0980-40eb-a4ed-7ed93a4f2765)

### Operating System

Windows 10

### DeepLabCut version

DLC 2.3.5

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1.Using Conda Environment
2. Load in Deeplabcut gui "python -m deeplabcut"
3. Load Project - from .yaml in project folder
4. Go to label frames tab
5. select any folder that contains extracted frames
6. gui freezes then error messages come up

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by ocmistr** [comment]
I found that the napari, though installed, was not functioning properly. So I cleared my conda environment and cloned another and it is know working.

**Comment by ysmgrr** [comment]
Hello, I am facing the same issue for a while and cannot solve it.

Bug description

I am using the GUI version for a project. I can create the project, modify the config file and extract the frames. But when I click to label them, I get the following message:
![dlc1](https://github.com/DeepLabCut/DeepLabCut/assets/148891237/6b67f1d3-7f45-4c6f-acbc-ca301016905a)

Napari still opens and allows me to label the frames, storing .csv and .h5 files on the labeled-data project folder. If I reopen the folder in napari, I can see the previous labels I have addressed to each frame. However, I cannot use the check labels function since the same error appears and cannot do any of the following steps afterwards. Cleaning the environment and git cloning the repo again does not fix the error. 

Operating System
Windows 10

DeepLabCut version
2.3.9

Napari version 
0.4.18

DeepLabCut mode
single animal

Device type
GPU

**Comment by anthoni0n** [comment]
Hello, I have the same problem. 
What do you mean exactly by 'cleared my conda environment' and 'cloned another' ?


> I found that the napari, though installed, was not functioning properly. So I cleared my conda environment and cloned another and it is know working.
