### ISSUE TITLE
pose_cfg.yaml Not Being Created - no write access

### ISSUE THREAD

**Issue by lpereiras17** [DeepLabCut/DeepLabCut#2418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Our lab labeled in different computers and wanted to train on a different one. DLC recognized that all frames were labeled using “dlc.check_labels(…)”, but when creating a training dataset DLC doesn’t make the pose_cfg.yaml file in the dlc-models directory.

Please see the error below and let me know if you have any advice:

```
/mnt/home/pereir53/Downloads/VidPro-LPS-2023-10-14/labeled-data/CT55,2022-02-23,18-38-38/CollectedData_LPS.h5  not found (perhaps not annotated).
Downloading a ImageNet-pretrained model from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 913,in create_training_dataset
    model_path, num_shuffles = auxfun_models.check_for_weights(
  File "/usr/local/lib/python3.9/dist-packages/deeplabcut/utils/auxfun_models.py", line 70, in check_for_weights
    download_weights(modeltype, model_path)
  File "/usr/local/lib/python3.9/dist-packages/deeplabcut/utils/auxfun_models.py", line 96, in download_weights
    tar.extractall(path=target_dir)
  File "/usr/lib/python3.9/tarfile.py", line 2036, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.9/tarfile.py", line 2077, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.9/tarfile.py", line 2150, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.9/tarfile.py", line 2191, in makefile
    with bltn_open(targetpath, "wb") as target:
**OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.9/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'**
```

### Operating System

Windows, Institute for Cyber Enabled Research (Michigan State University)

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @lpereiras17, the issue here seems to come from the pre-trained model weights not being downloaded correctly. This is likely because your python script does not have "write" access to the folder where DeepLabCut is installed: `read-only file system`.

The easiest solution is to make sure you have the right to write files to that folder. Another way to do things would be to download the weights when creating the DeepLabCut environment (at which point you would have access to that folder): download the `ResNet50` weights from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz, and save them in `/usr/local/lib/python3.9/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt`.
