### ISSUE TITLE
Error in add_new_videos(extract_frames=True) but not extract_frames()

### ISSUE THREAD

**Issue by tsievert** [DeepLabCut/DeepLabCut#2461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm currently testing DLC on our HPC and noticed a strange behavior between `add_new_videos(extract_frames=True)` and `extract_frames()`.

When I try to extract frames via `add_new_videos(extract_frames=True)` I always get `Frame extraction failed. Video files must be corrupted.` but `extract_frames()` still works.
Switching between `copy_videos=False` and `copy_videos=True` has no effect.

### Operating System

Operating System: Red Hat Enterprise Linux 8.6 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-372.26.1.el8_6.x86_64

### DeepLabCut version

2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

This causes the error:
```
import deeplabcut

config_file_path = '/gpfs/projects/acad/behavior/DLC_model/primary_DeepLabCut_model/LassanceLab-main-model-2023-09-14/config.yaml'

video_file_path = ["/gpfs/projects/acad/behavior/videos/2023-11-13_conspecific_odor_videos/2023-09-15_test videos/cluster_test_vid.mp4"]

VideoType = 'mp4'

deeplabcut.add_new_videos(
    config_file_path,
    video_file_path,
    copy_videos=False,
    coords=None,
    extract_frames=True,
)
```

If you now run `deeplabcut.extract_frames(config_file_path, mode='automatic', algo='kmeans', userfeedback=False, crop=False)` the extraction suddently works.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Does it help if in you move this [line](https://github.com/DeepLabCut/DeepLabCut/blob/0f657cde513dad207c68e9bb16eab8d5c351fde5/deeplabcut/create_project/add.py#L141) to be above `if extract_frames:` (line 130)?

Since it passes the videos to `extract_frames` as a list that's used in `videos_list` there it performs a check: `videos = [v for v in cfg["video_sets"] if v in videos_list]`. This basically means that when passing `extract_frames=True`  in `add_new_videos` it performs a check before the config is changed and new videos are added. At least that's my quick guess

PS: if that's it please make a PR 😃

**Comment by tsievert** [comment]
I'm frankly not comfortable enough to mess with the DLC code 😅
I mean you saw my struggle with `video_file_path` and `[video_file_path]` in the forum, so messing with the code is far beyond my comfort zone
