### ISSUE TITLE
Colab using 1% of GPU 

### ISSUE THREAD

**Issue by Scottydoesntkno** [DeepLabCut/DeepLabCut#2465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've trained many models with no issues but since this Friday all of sudden GPU stop being utilized. It only uses the System RAM and 0.1 of the GPU RAM.

### Operating System

Mac OS

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by WILLOSCAR** [comment]
The same

**Comment by H-Dempsey** [comment]
I think the reason that Colab now uses 1% of the GPU is because Google made an [update to CUDA 12.2](https://github.com/googlecolab/colabtools/issues/4214) recently. Tensorflow-2.10.0 automatically installs on Colab, so it needs CUDA 11.2 and cuDNN 8.1 (according to the Linux GPU section [here](https://www.tensorflow.org/install/source#gpu)). A [temporary solution](https://github.com/googlecolab/colabtools/issues/4214) is to connect to a GPU runtime -> click tools -> command palette -> type in and select 'use fallback runtime'. But this will only work until early Jan unfortunately.

**Comment by n-poulsen** [comment]
Thanks for looking into this @H-Dempsey! We'll look into possible solutions

**Comment by H-Dempsey** [comment]
No worries @n-poulsen! I am also keen to help with this, as Colab is my main platform for using DeepLabCut. I can think of 2 potential solutions:

1. The first is to set the versions of CUDA to 11.2 and cuDNN to 8.1.x at the start of all the Colab notebooks.
    - We could [purge](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#removing-cuda-toolkit-and-driver) the previous CUDA version and download and [install](https://stackoverflow.com/a/59615803) CUDA and cuDNN. The downside is that you first need to create an NVIDIA Developer account to access the cuDNN installation files. I could do this, but I couldn't get past the issue of changing environment variables.
    - It would be much easier to use `conda install -c conda-forge cudnn==8.1.0.77 cudatoolkit==11.2.0`. There is a conda-forge package for both [cudnn](https://anaconda.org/conda-forge/cudnn) and [cudatoolkit](https://anaconda.org/conda-forge/cudatoolkit). To use conda on Colab, we need to install [condacolab](https://github.com/conda-incubator/condacolab). While we can't create virtual environments, it allows us to use conda commands on a base environment. I similarly had issues with environment variables after this.

2. The second is to make changes to the dependencies, so that tensorflow==2.15.0 does not give the [error](https://github.com/DeepLabCut/DeepLabCut/pull/2308) `ModuleNotFoundError: No module named 'tf_keras'`. 
    - tensorflow==2.15.0 is the [only version](https://www.tensorflow.org/install/source#gpu) that works with CUDA 12.2. There is a package called [tf-keras](https://github.com/keras-team/tf-keras), which [works specifically](https://github.com/keras-team/tf-keras/releases/tag/v2.15.0) with this version. I have tried doing `pip install deeplabcut[tf]`, `pip install tensorflow==2.15.0`, `pip install tf_keras` and then running the [demo notebook](https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb).
    - Unfortunately, there are a bunch of essential directories to DeepLabCut in the tf-keras repo that are not included in the pip install, such as `legacy_tf_layers`. I tried to add all the omitted directories manually, but this still leads to issues between tensorflow and keras.
    - We might need to create a custom fork of tf-keras and direct the user to install from there. But with each new version of tensorflow and CUDA that Colab wants, there may be more complicated modifications to tf-keras we need to make.

Option 1 may mean that we don't need to be prepared for new breaking changes between DeepLabCut and future versions of tensorflow. Option 2 however is in the spirit of what Colab wants, which is for users to update their scripts for the latest drivers. What do you think is the best approach?

Harry

**Comment by lithium0003** [comment]
Just run 
`!apt update && apt install cuda-11-8`
before `pip install deeplabcut[tf]`

**Comment by H-Dempsey** [comment]
Thank you @lithium0003! Colab works perfectly for me now

**Comment by bainro** [comment]
> Just run `!apt update && apt install cuda-11-8` before `pip install deeplabcut[tf]`

worked for me too!

**Comment by Scottydoesntkno** [comment]
Thank you so much!
