### ISSUE TITLE
Trajectory data "video+DLCscorer+.h5" file is not saved after deeplabcut.analyze_videos()

### ISSUE THREAD

**Issue by ziyingc** [DeepLabCut/DeepLabCut#2563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am doing maDLC project on Ubuntu and macOS.
I can run the step "dlc.analyze_videos()" step and generate the trajectory plot.

But i don't have .h5 or .csv file saved. but I have  ****_el.h5 file saved, which has labeled datapoints only.

### Operating System

operating system ubuntu and macOS

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

multi animal

### Device type

gpu on ubuntu and cpu on macOS

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @ziyingc! For multi-animal DeepLabCut projects, there is no `"video+DLCscorer+.h5"` or `"video+DLCscorer+.csv"` file saved. This is because, contrarily to single animal projects, each animal needs to be "assembled" from bodyparts and then tracked across time. You can read more about it in our [multi-animal user guide](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#animal-assembly-and-tracking-across-frames), where it's stated:

> Please note that you do not get the .h5/csv file you might be used to getting (this comes after tracking). You will get a pickle file that is used in create_video_with_all_detections. 

So the `_el.h5` and `_el.csv` files are the output of this assembly and then tracking (and are the files you should use to analyze your data). The `_el` suffix indicates that the ellipse tracker was used.

**Comment by ziyingc** [comment]
Oh, thanks. It has been solved.
