### ISSUE TITLE
FFMPEG Create labeled video 3d

### ISSUE THREAD

**Issue by CMGreenspon** [DeepLabCut/DeepLabCut#350]
Calling create labeled video 3d produces an error preventing video creation. It appears all of the relevant frames are created and are placed in the output folder with the appropriate names but FFMPEG/subprocess cannot find them.

```py
 File "<ipython-input-5-e293b8db4715>", line 1, in <module>
    deeplabcut.create_labeled_video_3d(config_path3d,[vid_dir],videotype='mp4',start=1790,end=1800, trailpoints=0)

  File "C:\Users\somlab\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_3d\plotting3D.py", line 140, in create_labeled_video_3d
    subprocess.call(['ffmpeg', '-start_number', str(start) ,'-framerate', str(30), '-i', str('img%0'+str(num_frames)+'d.png'), '-r', str(30),'-vb', '20M' ,os.path.join(output_folder,str('../'+file_name+'.mpg'))])

  File "C:\Users\somlab\Anaconda3\envs\dlc-windowsGPU\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\somlab\Anaconda3\envs\dlc-windowsGPU\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "C:\Users\somlab\Anaconda3\envs\dlc-windowsGPU\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Windows 10
DLC 2.0.7.1

**Comment by MMathisLab** [comment]
Please do not ignore the template. You need to provide:

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [e.g. iOS, Windows 10, etc]
DeepLabCut Version [e.g. 22] (please check with `import deeplabcut, deeplabcut.__version__`)
Browser [e.g. chrome, safari]


**Describe the problem**

A clear and concise description of what the problem is.

**How to Reproduce the problem**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Screenshots**
If applicable, add screenshots to help explain your problem.


**Additional context**
Add any other context about the problem here.




Q: Does your ffpmeg otherwise work? It's not a bug, etc in the code we can reproduce here.

**Comment by CMGreenspon** [comment]
Ah, so I didn't realize FFMPEG wasn't included in the DLC install. Is it possible to have a comment added to the install instructions?

**Comment by MMathisLab** [comment]
Typically it is downloaded the first time it’s called, just you’re not using terminal as an admin therefore you don’t have the correct permissions at the time.

**Comment by CMGreenspon** [comment]
Is that definitely the case in Windows and not just in Linux?

**Comment by MMathisLab** [comment]
yep.
