### ISSUE TITLE
Export directory print statement

### ISSUE THREAD

**Issue by CMGreenspon** [DeepLabCut/DeepLabCut#366]
Minor detail:
When analyzing videos with destination folder set the output information still declares that files are being saved to the parent directory of the videos. Line 335 (v 2.0.7.2, line 329 in v 2.0.7.1) is not conditional upon the destfolder input.

Windows 10, DLC 2.0.7.1 (though unchanged in 2.0.7.2)

**Comment by AlexEMG** [comment]
@CMGreenspon, thanks for raising this?

Can you elaborate what the problem is? -- for me this functionality works (i.e. the h5 and pickle files are saved in the specified folder)

The code: 
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L284
"uses" the destination folder when the user passes a folder (rather than None). However, if the folder is None, then the root folder of the video is used (i.e. the results are stored in the same folder as the video itself.

**Comment by CMGreenspon** [comment]
Sorry, I wasn't specific enough. The file export itself is fine. But the terminal output on line 335 "print("Saving results in %s..." %(Path(video).parents[0]))" does not update to the destination folder if declared. So even though the file is saved in the correct location the user is told otherwise. 

If it instead said:

print("Saving results in %s..." %(destfolder))

it would output/print correctly.

**Comment by AlexEMG** [comment]
Thanks, that's great! Will update the code, you can also send a PR if you want.

**Comment by MMathisLab** [comment]
will be updated in 2.0.8 thanks for noticing this @CMGreenspon
