### ISSUE TITLE
Lack of smooth tracking

### ISSUE THREAD

**Issue by kgj1234** [DeepLabCut/DeepLabCut#369]
Training on recordings of motion tracking for mice showed occasional momentary deviations from the true mouse position. This can probably be fixed in post processing by identifying outlying data points and interpolating, but I was wondering if you had considered adding a recurrent layer to your network, to allow passage of the predicted position in the prior frame as input for the current frame.

**Comment by AlexEMG** [comment]
Dear @kgj1234,

You're right -- the short answer: when the labeling is good enough filtering is not required in our experience. There are filters included in DLC if this is needed (see below).

Long answer:
We have thought about this -- in the original paper [DeepLabCut: markerless pose estimation of user-defined body parts with deep learning](https://www.nature.com/articles/s41593-018-0209-y), we write:

"As presented, DeepLabCut extracts the posture data frame by frame, but one can add temporal filtering to improve performance (as for other approaches). Here we omitted such methods because of the high precision of the model without these additional steps, as well as to highlight the accurate prediction based on single frames **solely driven by within-frame visual information** in a variety of contexts.

While temporal information could indeed be beneficial in certain contexts, challenges remain to using end-to-end-trained deep architectures for video data to extract postures. Because of the curse of dimensionality, deep architectures on videos must rely on input images with lower spatial resolution, and thus the best-performing action recognition algorithms still rely on frame-by-frame analysis with deep networks pretrained on ImageNet as a result of hardware limitations. As this is an active area of research, we believe this situation is likely to change with improvements in hardware (and in deep learning algorithms), and this should have a strong influence on pose estimation in the future. Therefore currently, in situations where occlusions are very common, such as in social behaviors, pairwise interactions could also be added to improve performance. Here we have focused on the deep feature detectors alone to demonstrate remarkable transfer learning for laboratory tasks without the need for such extensions."

I omitted the references for clarity here - but you can find them in the paper. The package allows filtering as post-processing, after inference. You can use it by:

```deeplabcut.filterpredictions```

The docs state:
```Signature: deeplabcut.filterpredictions(config, video, videotype='avi', shuffle=1, trainingsetindex=0, p_bound=0.001, ARdegree=3, MAdegree=1, alpha=0.01, save_as_csv=True, destfolder=None)
Docstring:
Fits frame-by-frame pose predictions with SARIMAX model.

Parameter
----------
config : string
    Full path of the config.yaml file as a string.

video : string
    Full path of the video to extract the frame from. Make sure that this video is already analyzed.

shuffle : int, optional
    The shufle index of training dataset. The extracted frames will be stored in the labeled-dataset for
    the corresponding shuffle of training dataset. Default is set to 1

trainingsetindex: int, optional
    Integer specifying which TrainingsetFraction to use. By default the first (note that TrainingFraction is a list in config.yaml).

comparisonbodyparts: list of strings, optional
    This select the body parts for which SARIMAX models are fit. Either ``all``, then all body parts
    from config.yaml are used orr a list of strings that are a subset of the full list.
    E.g. ['hand','Joystick'] for the demo Reaching-Mackenzie-2018-08-30/config.yaml to select only these two body parts.

p_bound: float between 0 and 1, optional
    For outlieralgorithm 'uncertain' this parameter defines the likelihood below, 
    below which a body part will be consided as missing data for filtering purposes.

ARdegree: int, optional
    For outlieralgorithm 'fitting': Autoregressive degree of Sarimax model degree.
    see https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html

MAdegree: int
    For outlieralgorithm 'fitting': Moving Avarage degree of Sarimax model degree.
    See https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html

alpha: float
    Significance level for detecting outliers based on confidence interval of fitted SARIMAX model.

save_as_csv: bool, optional
    Saves the predictions in a .csv file. The default is ``False``; if provided it must be either ``True`` or ``False``

destfolder: string, optional
    Specifies the destination folder for analysis data (default is the path of the video). Note that for subsequent analysis this 
    folder also needs to be passed.

Example
--------
deeplabcut.filterpredictions('C:\myproject\reaching-task\config.yaml',['C:\myproject\trailtracking-task\test.mp4'],shuffle=3,ARdegree=5,MAdegree=2)

One can then use the filtered rather than the frame-by-frame predictions by calling:
    
deeplabcut.plot_trajectories('C:\myproject\reaching-task\config.yaml',['C:\myproject\trailtracking-task\test.mp4'],shuffle=3,filtered=True)

deeplabcut.create_labeled_video('C:\myproject\reaching-task\config.yaml',['C:\myproject\trailtracking-task\test.mp4'],shuffle=3,filtered=True)
--------

Returns filtered pandas array with the same structure as normal output of network.```

Hope that helps! There will be some additional filters in the future, so stay tuned!

**Comment by kgj1234** [comment]
Thanks for your response.

**Comment by monajalal** [comment]
could you please show a little more step by step how to use the smooth filtering for making use of the fact that the input is a video and not a single frame? for example, the current frame correlates with the past frame(s).

Can we do smooth filtering or tracking using the GUI or could you suggest how this could be done?>

I wonder if I can do this given the CSV I get after the training?

Any help is really appreciated.

**Comment by AlexEMG** [comment]
The filter is applied after/during the video analysis. 
https://github.com/AlexEMG/DeepLabCut/blob/53a784b95a0d31b403deab0541b4770fd001448f/docs/functionDetails.md#i-novel-video-analysis-extra-features
