### ISSUE TITLE
Analysis completely failed. Not sure what I did wrong (setting myconfig files...)

### ISSUE THREAD

**Issue by bill-connelly** [DeepLabCut/DeepLabCut#37]
So after training my network for a week on a CPU, I used MakingLabeledVideo_fast.py, however, the output video is identical to the input video, i.e. no parts are labelled.

You can see there was a slight error when the code ran, but it didn't look fatal to me.

I then ran through the code manually and I've seen a big problem

On line 65 of MakingLabeledVideo_fast.py:
bodyparts2plot = list(np.unique(Dataframe.columns.get_level_values(1)))
The value of bodyparts2plot is ['Finger1', 'Finger2', 'Joystick', 'hand'], which are the values from your supplied data, not what I entered in myconfig.py

Obviously, somewhere something has been pointed to the wrong thing, but I have no idea where.* Clues that might help in the directorys:
C:\Users\wmkc\Documents\DeepLabCut\Evaluation-Tools\LabeledImages_DeepCut_resnet_50_95shuffle1_170000forTask_reachingbill

and

C:\Users\wmkc\Documents\DeepLabCut\Generating_a_Training_Set\data-reachingbill\datalabeled

The training data is appropriately labelled.

The other big thing is that my network was trained 170000 iterations, not 37500 iterations. Which again, is what I think your one is trained to. So where have I gone wrong? 

Any help deeply appreciated.

*For what it's worth, this is consistently the area I am having problems with while using DLC. I'm of course **extremely** grateful for your supplying the community with your code. But I have not found the instructions on how to set up the config files, or the path structure clear. For instance in myconfig.py, lines 14 through 18, it is not clear what these values should be. Are they relative paths, [if so, relative to what?] complete paths, and what should be in this path?

(DLCdependencies) C:\Users\wmkc\Documents\DeepLabCut\Analysis-tools>python MakingLabeledVideo_fast.py
Starting  ../videos/ ['mouse_reaching_crop.avi']
Loading  mouse_reaching_crop.avi and data.
The video was not analyzed with this scorer: DeepCut_resnet50_reachingJan30shuffle1_500
Other scorers were found, however: ['mouse_reaching_cropDeepCut_resnet50_reachingJan30shuffle1_37500.h5']
Creating labeled video for: mouse_reaching_cropDeepCut_resnet50_reachingJan30shuffle1_37500.h5  instead.
Duration of video [s]:  195.02 , recorded with  50.0 fps!
Overall # of frames:  9751 with cropped frame dimensions:  358 465
Generating frames
100%|#############################################################################| 9751/9751 [01:09<00:00, 139.41it/s]

**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Bill, these are not GitHub issues. Ie there isno issue with the code, it is just help requests. We will ask again, can you please email us to join the slack group.

**Comment by AlexEMG** [comment]
For completeness - Given your description I suspect that you trained + evaluated your network correctly (by editing myconfig.py). For analyzing videos + labeling them you need to define which network to use, and this is done my editing [```myconfig_analysis.py```](https://github.com/AlexEMG/DeepLabCut/blob/master/myconfig_analysis.py) accordingly. 

Please note that a lot of descriptions are inside the configuration files themselves & of course in the [docs](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/analysis-tools.md), which starts by stating that editing the ```myconfig_analysis.py``` is the first step. 

I hope this makes sense now? - anyway, we would be delighted to hear how we could make the documentation clearer, based on your experience.

**Comment by bill-connelly** [comment]
> we would be delighted to hear how we could make the documentation clearer, based on your experience.

In instruction 0 "The "myconfig.py" file and set the global variables for your dataset" It would probably be useful to be told which ones are crucial [i.e. would need to be changed when the user runs their own data].

in myconfig there are variables for Scorers, date and scorer. Why are they important? What should we set them to? Because they sound like it's unimportant.

 For me, the biggest confusion is that if you skip step 1, it is not written anywhere (as far as I can see) how you steer DLC to your TIFFs.

A similar problem occurs in myconfig_analysis. It's relatively clear how you steer DLC to the videos the be analyzed, but how do you choose which network to use?

**Comment by AlexEMG** [comment]
*A similar problem occurs in myconfig_analysis. It's relatively clear how you steer DLC to the videos the be analyzed, but how do you choose which network to use?*

A network is uniquely defined by: date, task, fraction & shuffle, i.e. see the example folder.
reachingJan30-trainset95shuffle1
You want to change those 4 variables to access the correct one. However, a given folder might contain different snapshots (training iterations), so you should adjust the snapshot index accordingly.

*in myconfig there are variables for Scorers, date and scorer. Why are they important? What should we set them to? Because they sound like it's unimportant.*

date (see above). Perhaps one trains different networks on different dates etc. Scorers is mostly important for users, who will also evaluate the accuracy of one / different human scorers... [mostly irrelevant for the general users]

*For me, the biggest confusion is that if you skip step 1, it is not written anywhere (as far as I can see) how you steer DLC to your TIFFs.*

Try to mimic the data structure ```step1...``` generates. I.e. data-*task* 
Then update the task variable in ```myconfig.py```. That should be it. 

*In instruction 0 "The "myconfig.py" file and set the global variables for your dataset" It would probably be useful to be told which ones are crucial [i.e. would need to be changed when the user runs their own data].*

Fair enough. Maybe some more text is needed. 

We are also happy to get PRs involving doc updates.
