### ISSUE TITLE
CPU core number use [tensorflow]

### ISSUE THREAD

**Issue by bkacsoh** [DeepLabCut/DeepLabCut#391]
**Your Operating system and DeepLabCut version**
MacOS Version 10.13.4, DeepLabCut 2, with conda environment dlc-macOS-CPU

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: iOS
DeepLabCut Version 2
Browser firefox

**Describe the problem**

Hello, 

I am wondering how to tell the code to run on a partition of cores--i.e. I have 4 cores and would like to run the commands on 3 of the 4 available cores, etc. I would like this so that I may run multiple partitions at once.

**Comment by MMathisLab** [comment]
Because CPUs are very very slow (see below), we have focused on GPU computations. However, you can set the cores within tensorflow: https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core

Image from: https://www.biorxiv.org/content/10.1101/457242v1.full

![image](https://user-images.githubusercontent.com/28102185/62567670-a87ee780-b859-11e9-88b7-a0cc6cecf0e5.png)

**Comment by bkacsoh** [comment]
Thank you so much!
