### ISSUE TITLE
selecting frames for labeling (Windows 10)

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#393]
**windows 10, anaconda env for CPU, deepcutlab 2.0.8 **
OS: Windows 10
DeepLabCut Version [2.0.8] 
Browser: chrome
using Jupyter notebook

**Describe the problem**
when running Demo_yourowndata using Jupyter notebook (and also "Manually correct labels" in other demos)
 I extracted frames and I can see them in the folder C:\Users\Admin\DeepLabCut\examples\shachaf\swimming-shachaf-2019-08-08\labeled-data\night1
![Picture1](https://user-images.githubusercontent.com/53897118/62689942-6a5a0300-b9d4-11e9-9184-d8649b72810d.png)
![Picture2](https://user-images.githubusercontent.com/53897118/62690008-91183980-b9d4-11e9-8445-6a93b27fe585.png)
 
but when I tried to open them for labeling via gui it doesn't show the files and I can't select them.
 ![Picture3](https://user-images.githubusercontent.com/53897118/62690157-df2d3d00-b9d4-11e9-809f-902fcd03be13.png)

Thank you very much in advance,
your software is super impotent for the success of my research :)

**Comment by MMathisLab** [comment]
If you click select folder, what happens?

**Comment by DataBeeGood** [comment]
Presuming this is not an essential issue in DeepLabCut...
Some thoughts on quirky annoyances in Windows that this resembles.

1. First 2 screenshots indicate Users/admin/.... 3rd does not show full path...I**s the selector for the target folder accessing as ADMIN ?**
2. I can't tell from 3rd image...**Which folder are you actually in as you seek the night1 folder?**  Are you in labeled-data **selecting** night1 folder or have you accidently **opened** night1 folder?
You need to be in the super directory to select a FOLDER...  and so accidently clicking on the folder can open it - (esp. if your windowsOS preferences allow "single click" rather than "double click" in order to open folder)... OR programmatically it accidently opens the folder rather than selecting it and remaining in the super directory...  (which can happen when there are manual vs automated folder selection options) 

Good Luck...

**Comment by Shachafbe** [comment]
All folders were accurate. 
Before, when I pressed "select folder" nothing happened, but after playing with it for a bit now I still don't see the files in the selection window but by pressing "select folder" it opens the frames for labeling. 
Tried a few minor things, not exactly sure what helped but its works now.

Thank you very much for the quick response and please accept my apologies for taking your time!

**Comment by MMathisLab** [comment]
sometimes in windows it doesn't show the images, but it always lets you select the folder, glad it's just that!

**Comment by Angel113110** [comment]
@Shachafbe  I met the same question you met before. When I click the button and select the folder, I can't see any pictures. The frame used for labeling also can't work. How to deal with this problem?

**Comment by MMathisLab** [comment]
You select the folder, hit okay. Click help button for instructions. It’s a right click to label
