### ISSUE TITLE
question about 3D calibration using a mirror for bottom view

### ISSUE THREAD

**Issue by ma79** [DeepLabCut/DeepLabCut#495]
OS: Windows 10
DeepLabCut Version: 2.1.3
Env: Anaconda 
Browser: chrome

**Describe the problem**

Hello,

I am trying to use the 3D features using one camera to capture a side view and a reflected bottom view of a mouse crossing a clear platform (splitting the side and bottom views into separate videos).  The bottom views are then flipped along the horizontal axis to make it seem that the camera is below the platform.  

I used images of a checkerboard taken the same way for calibration.  All the corners for both views are correctly detected assigned, but when I run the check_undistortion, it seems to map the points off of the images somewhere in 3D-space (most of the mapped images are just black).  The locations of the checkerboard in the 3D plot don't move in the x-axis, which is how I moved it in the calibration pictures.

Is this because the 2nd "camera" is looking from the bottom (or is from a reflection?).  Are there restrictions to where the cameras can be placed in relation to each other or some way to tell deeplabcut that the image is from below?

I've attached a couple of the corners images and 3D plot.  Let me know if I'm not being clear with this.  Thanks for your help

Thong

![checkerboard_3d](https://user-images.githubusercontent.com/57957737/69168127-17f4ac00-0ac4-11ea-976f-868f7ca7690e.png)

![camera-1-06_corner](https://user-images.githubusercontent.com/57957737/69168171-30fd5d00-0ac4-11ea-9a01-1c32ba70c4f0.jpg)

![camera-2-06_corner](https://user-images.githubusercontent.com/57957737/69168189-3a86c500-0ac4-11ea-8cfb-7078ede8193c.jpg)

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Hi @ma79 - note the the X in 2D pixel space is not necessarily the X in the 3D space. The 3D plot looks reasonable, to me, but of course I don' know your data. How does the actual DLC outputs look in 3D?

**Comment by ma79** [comment]
Hi,

Thanks for the reply.  The DLC output of the mouse crossing horizontally on the platform follows an arc similar to what is seen on the 3D plot (and not appearing to be on a flat surface).  

For the calibrations, the undistorted images appear all black and not mapped back to the checkerboard like in your instructional video.  I've attached the undistorted_points image which shows the points not mapping back to the image.  I assume that the points should be in the space where the images are?  

Also, is this not the best place to ask you a question like this?  If not, where should I post this question?

Thanks,

Thong


![undistorted_points](https://user-images.githubusercontent.com/57957737/69465391-125ec680-0d4f-11ea-9c5f-bcd453b968d2.png)

**Comment by MMathisLab** [comment]
Questions are indeed best on Image Forum: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

That does look far off the space though; the alpha values has some constraints on this. But in general, the 3D code we use in from openCV assumes a stereo pair of cameras. https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_3d/camera_calibration.py


@ma79-  are you trying to use the a mirrored version of the calibration board? That will not work... the board is used to compute the intrinsic camera parameters, and by using the mirror you are messing this up quite a lot. You need to take an image such that it's only trying to correct for the lens distortion. So, in short, that is likely the issue is that 1) not a stereo pair, 2) it cannot correctly compute the disotorions given how you are taking pictures of the checkerboard.

**Comment by ma79** [comment]
Thanks @MMathisLab and @michaelfsp for the info on the 3D calibration.  I was thinking that the issue is that it wasn't a stereo pair.  Do you have any suggestions for frameworks to translate the bottom and side views into 3D space?

**Comment by MMathisLab** [comment]
You can try the other openCV functions, or perhaps www.anipose.org (another 3D wrapper for DLC)
