### ISSUE TITLE
With Existing Tools - Advice for Multiple-Animal Labeling?

### ISSUE THREAD

**Issue by xdhmoore** [DeepLabCut/DeepLabCut#509]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

_Windows 10 (Anaconda, DLC 2.1.3) and Red Hat Linux 7 (Anaconda, DeepLabCut 2.1.4)_

Please complete the following information about your system:

OS: _Windows 10 (for labeling) & Red Hat Linux 7_
DeepLabCut Version: _2.1.3 for labeling, 2.1.4 otherwise_
Browser [e.g. chrome, safari]: _Firefox_

**Describe the problem**

I see several issues discussing multiple animal workflows, especially how to use scoremaps and thresholds to use a trained network to mark multiple animals. And mentions of future tooling. But my question is related to labeling multiple animals using existing tools. I was wondering if you had any advice. 

I am trying to label aerial data of multiple sharks in ocean waters. Let's say for example there are 5 sharks in an image. Using existing tools, I could label a single shark and ignore the others in the image. Or, I could copy that image 5 times and then label a different shark in each of 5 duplicate images. Do you have any thoughts on which would be more effective? Or maybe there are other strategies I haven't considered.

**Screenshots**
This a frame from one of the clearer video segments. The tagging results are a work in progress.
![Training-agg3-img090](https://user-images.githubusercontent.com/5142129/69921432-761b7a80-1446-11ea-9ea3-eeca37af2139.png)

**Comment by MMathisLab** [comment]
We please ask you don't ask user help questions on github - this is for bug reports. Please see: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

DLC currently only supports single animal tracking. Updates will be available in the near future. We have a [multi-animal labeling GUI](https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/multiple_individual_labeling_toolbox.py) (actually since Feb), but it is currently not documented and training code is not provided, this will be updated in the near future to allow for users to track multiple animals. If you are not tracking posture though, you should use a tool such as idtracker.ai 

If you wish to search issues and post for help, please post on the Image Forum with the tag deeplacut. https://forum.image.sc/tags/deeplabcut

**Comment by xdhmoore** [comment]
Ok, thanks. I'll check those out.

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.
