### ISSUE TITLE
Object labels jump and results 

### ISSUE THREAD

**Issue by JXXCgit** [DeepLabCut/DeepLabCut#510]
Hi, I am using the DLC to analyse my video(3.5GB/1 hour, 1920*1080 in pixels, 15fps). I do the training with 20000 iterations, MobileNet (since my video is large, so i do not set up the iteration times higher), 
and the training results is :
Results for 20000  training iterations: 95 1 train error: 1.57 pixels. Test error: 7.43  pixels.
With pcutoff of 0.1  train error: 1.57 pixels. Test error: 7.43 pixels
Next i continue the following steps, and finish all the procedures. 
I tried to open the filtered video produced by the program and i found there are several problems:
one is the label animal is not the one i labeled for training before(i have many animals within one video and most of animals are marked with number tag) and the label objects jump to another animals with another number tag or even jump to animals without number tag, and sometimes even jump to the wall of the space where the animals live. 
the second is the results of the plot_poses, they alĺ look ugly: 
![hist_filtered](https://user-images.githubusercontent.com/40397232/69947140-50957c00-14ed-11ea-8a0d-f9267304e5bc.png)
![plot_filtered](https://user-images.githubusercontent.com/40397232/69947141-50957c00-14ed-11ea-90aa-7e032c29ae74.png)
![plot-likelihood_filtered](https://user-images.githubusercontent.com/40397232/69947142-50957c00-14ed-11ea-8dca-80de44678c36.png)
![trajectory_filtered](https://user-images.githubusercontent.com/40397232/69947143-50957c00-14ed-11ea-9e29-be593ec086ad.png)

I am a freshman to use DLC, can you please help me to figure out what the problem would be? 
And can i use the compressed video to analyse, since i have many big video and it would take  quite a lot of time to do it?
Thank you for help. 
Best regards
Chen

**Comment by MMathisLab** [comment]
@shauyin520 Chen, we please ask you **don't** ask user help questions on github - this is for bug reports, and when you use this medium you need to follow the templates. We cannot help otherwise. Please see: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help 

The performance of any network is going to be on how much labeled data, how good your data is, and how long you train for. DLC currently only supports single animal tracking. Updates will be available in the near future. If you wish to search issues and post for help, please post on the Image Forum with the tag deeplacut. https://forum.image.sc/tags/deeplabcut

**Comment by JXXCgit** [comment]
Thank you for the information. 
Best
CHen
