### ISSUE TITLE
Functions not working with no error message

### ISSUE THREAD

**Issue by eleonoreduroyon** [DeepLabCut/DeepLabCut#541]
**Your Operating system and DeepLabCut version**

Ubuntu 18.04.3 LTS with Anaconda Env & DLC version 2.1.1 (using a GPU as well)

**Describe the problem**

I recently updated to Ubuntu 18.04.3. I had a few issues but now everything works (labeling and training). However, after training, I tried to filterpredictions and plot_trajectories. Neither are working and I am not getting an error message even when the video path is nonsense. Can anyone help?

**Screenshots**
![Screenshot from 2020-01-10 11-30-20](https://user-images.githubusercontent.com/32446840/72180745-a686fa80-339c-11ea-98b6-1315d546d129.png)

**Comment by johnmbarrett** [comment]
This has happened to me before, usually I find when DeepLabCut function calls exit "successfully" with no error messages but no results either it means DLC can't find the videos you told it to look for. ~~You're trying to analyse MP4s but have `videotype='.avi'`, so DeepLabCut finds no videos and successfully doesn't analyse them, hence no error. Set `videotype='.mp4'` in each of the function calls and they should work.~~ This is a slightly poor user experience IMO, it would be better to have the extension (if passed) override the `videotype` parameter and/or throw a warning if no videos are found, rather than just silently exiting.

**EDIT**: actually, re-reading your log I see you have passed `videotype='.mp4'`. In that case I'd guess DeepLabCut is not finding your videos for some other reason.
