### ISSUE TITLE
GPU not used [how to user docker]

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#546]
Hi, Dear all,  
My opperating system is 
Ubuntu 18.04.3 LTS, Memory is 31.4 GB, Processor: Intel Core i7-3820 CPU@3.6GHzx8, Graphcis: GeForce GTX680/PCle/SSE2, GNOME:3.28.2, OS type 64-bit; dICK: 1.1 TB
DLC version: 2.1.3
Cuda version:10.2 
Tensorflow: 1.14.0 
I follow this link: https://github.com/DeepLabCut/Docker4DeepLabCut2.0 to run the DLC in Docker2 
One thing i am struggling is: i am not sure whether the GPU is using or not. I check my nividia card state from both two ways as followed, it looks like the GPU is not used! 
![Screenshot from 2019-12-27 16-48-04](https://user-images.githubusercontent.com/59871930/72344883-ace5e100-36d2-11ea-9dce-1e49fb402d38.png)
![Screenshot from 2020-01-13 10-08-59](https://user-images.githubusercontent.com/59871930/72344884-ad7e7780-36d2-11ea-8cc8-3cc93cec3040.png)
So what the problems would be?  am i following the right way to use docker-gpu? 
One strange thing remind me is: when i using docker and run the DLC in the terminal step by step, everything seems to be fine in the docker enviroment, please see the red part as followed: 
![Screenshot from 2020-01-14 14-14-09](https://user-images.githubusercontent.com/59871930/72348225-3d73ef80-36da-11ea-906c-584f6da181ef.png)
until i import DLC and using it to do the training, the directory change to the directory i run the DLC using conda enviroment with CPU?
![Screenshot from 2020-01-14 14-20-47](https://user-images.githubusercontent.com/59871930/72348691-38fc0680-36db-11ea-9ce9-95e2e6934602.png)
somthing wrong here? is it related with the issue that the GPU is not used? 

And another question, i wonder if the GPU  not being used for DLC is because the my graphic card is too old? If yes, does it works with replacing the graphic card? or a totally new and better computer? 
Really thank you for the helpful suggestions!! 
Greetings,

**Comment by MMathisLab** [comment]
Hi @honigcheung I would prefer Docker issues be one the GitHub repo for Docker, but I can answer here. See your screenshot that states that there is an *error with the docker daemon*- the name "containername" is already in use, as you have linked to the same port many times. You need to remove these, as you can only have ONE. Also you can delete the exited containers. Please see here: https://github.com/DeepLabCut/Docker4DeepLabCut2.0#docker-quick-tips

Also, you call and set -e twice, for home, be sure you create this correctly. I would suggest just trying this:

`GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME --name dlctorben dlc_torben/dlcdocker`

Also, your GPU is too small to be useful for DLC; we recommend something >~1080 Ti. See here: https://github.com/AlexEMG/DeepLabCut/wiki/FAQ

I would also strongly advise against putting special characters into folder names, i.e. #203_xyz is not a great idea.

**Comment by JXXCgit** [comment]
Hi， Dear Mackenzie, 
Thank you for the nice help. I think the docker it self works, but the problem is the use of GPU. 
I watch through your video("Tutorial Part I: DeepLabCut- How to create a new project, label data, and start training" in youtube).  the directory when you run the DLC before and after with docker is different, as this: 
before using docker: <img width="1440" alt="Screen Shot 2020-01-16 at 9 40 05 AM" src="https://user-images.githubusercontent.com/40397232/72507689-a7100d00-3844-11ea-8b39-890c28faec9f.png">
after using docker: <img width="1440" alt="Screen Shot 2020-01-16 at 9 36 06 AM" src="https://user-images.githubusercontent.com/40397232/72507695-a8413a00-3844-11ea-8551-da030074a4d1.png"> 
I also notice that when you enter docker, you did not use command:
~$ cd Docker4DeepLabCut2.0 
for me:  before enter the docker, I put the command in as :
~$ cd Docker4DeepLabCut2.0 
~$ docker exec --user $USER -it containername /bin/bash
~$ cd ../../../home/
~$ ipython
~$ Linux: export DLClight=True
In [1]: import deeplabcut
before the step as "~$ Linux: export DLClight=True
                                 In [1]: import deeplabcut", my directory shown in the terminal was marked in the red : 
![72348225-3d73ef80-36da-11ea-906c-584f6da181ef](https://user-images.githubusercontent.com/40397232/72508555-27833d80-3846-11ea-8cf9-ebd1f7e94607.png)
but after import the deeplabcut in the docker, the directory in the terminal change to "IPython:home" again, which is the same directory as when I use the anaconda with cpu to run DLC, please see the red mark: 
![72348691-38fc0680-36db-11ea-9ce9-95e2e6934602](https://user-images.githubusercontent.com/40397232/72508686-6e713300-3846-11ea-95ad-11da72262d4a.png)
so I just wonder it is the problem here? 
thank you for your suggestion. 
Greetings
