### ISSUE TITLE
Description of loss functions that are being tracked for tensorboard

### ISSUE THREAD

**Issue by zashwood** [DeepLabCut/DeepLabCut#562]
Hi, thank you very much for DeepLabCut - we've just started using it and it's great.  

Quick Q: are you able to write down in math (or words) the three loss functions that are being tracked for visualization with Tensorboard?  i.e. What are locref_loss, part_loss and total_loss?  

Thanks!

**Comment by AlexEMG** [comment]
Total loss is the sum of the _cross-entropy loss_ between target score maps and predicted score maps and the _locref loss_.

The locref_loss is the L1-distance between the actual body part location (in image coordinates) and the retransformed image coordinates for a given pixel. This loss is to counteract the discretization effects due to downsampling along the ResNet/MobileNet.

One can also change the weighing of the two losses with the variable: _locref_loss_weight_
https://github.com/AlexEMG/DeepLabCut/blob/9a129d4946323799cf4328ec567f237ecde8c24d/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py#L178

**Comment by zashwood** [comment]
Thank you very much!
