### ISSUE TITLE
Hello I have question 

### ISSUE THREAD

**Issue by VISWIK** [DeepLabCut/DeepLabCut#617]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [e.g. iOS, Windows 10, etc]
DeepLabCut Version [e.g. 22] (please check with import deeplabcut, deeplabcut.__version__)

**Describe the problem**

A clear and concise description of what the problem is.

Please understand me if I do not know well.
Hello I have a question about why the example [reaching video]'s labeled image name increase randomly?
 
**How to Reproduce the problem**

**Screenshots**
![image](https://user-images.githubusercontent.com/61525617/76392194-651ec580-63b4-11ea-99c9-74f4c69c2ed4.png)

**Additional context**

**Comment by hugofluhr** [comment]
This is probably due to the fact that only a subset of the frames from a given video are used to train the network.
When you use the `deeplabcut.extract_frames()` function, it will take only `numframes2pick` frames per video (defined in the config file) for the user to label. The selection method depends on the arguments you pass to `extract_frames()` (for details see [function details](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#c-data-selection-extract-frames) ).
So any time you look into the labeled-data folder corresponding to a video, you will see that only a subset of frames are contained in the folders, these are the frames that you can label through the GUI and that will be fed to the network during training.
I hope this makes sense.
