### ISSUE TITLE
error while executing evaluate_network

### ISSUE THREAD

**Issue by manishinala** [DeepLabCut/DeepLabCut#627]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: MacOS 10.51, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: MacOS
DeepLabCut Version: 2.1.6.2
Browser: Safari

**Describe the problem**

I was able to execute the training part efficiently and when I am trying to evaluate the training network I am getting this error. Can you please help me out here. 

**How to Reproduce the problem**
**Screenshots**
<img width="1374" alt="Screen Shot 2020-03-20 at 9 18 10 PM" src="https://user-images.githubusercontent.com/22319037/77216415-87b98880-6af0-11ea-9d29-dc2f279f50cc.png">

**Additional context**
I was unable to execute the rest of the commands because of this error

**Comment by manishinala** [comment]
And I was unable to plot the graphs as well. 
<img width="1432" alt="Screen Shot 2020-03-20 at 9 23 40 PM" src="https://user-images.githubusercontent.com/22319037/77216513-2e058e00-6af1-11ea-9cf9-3b2ab92cfa24.png">

**Comment by MMathisLab** [comment]
We need the full input you ran, and the full output. Please copy/paste as formatted code ie use the icon <> to format correctly. Otherwise we cannot know what happened... please provide a complete template with a minimal example of how you got to this point and what was run. 

also it looks like you are using COLAB, not MacOS as the system where you are running the code. Did you train the network and be sure the snapshots are saved before you stopped it? Otherwise there is nothing to evaluate, analyze/plot.
