### ISSUE TITLE
Triangulation error

### ISSUE THREAD

**Issue by paulavillafulton** [DeepLabCut/DeepLabCut#633]
**Linux- Ubuntu 16.04.6 LTS with Anaconda Env and DeepLabCut version 2.1.6.2**

Please complete the following information about your system:

OS: Linux
DeepLabCut Version 2.1.6.2
Browser: chrome

**Describe the problem**

I am trying to follow the steps of "Demo 3D DeepLabCut" but when arriving to "Triangulation --> converting your 2D to 3D!" I run into the following error:
```

Strange naming convention on your part. Respect.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-15-ce605166a4d2> in <module>
      4 video_path = '/home/dlc/Desktop/DeepLabCut-master/examples/videos-raw/'
      5 
----> 6 deeplabcut.triangulate('/home/dlc/Desktop/DeepLabCut-master/examples/testing2-Paula-2020-03-20-3d/config.yaml',video_path, videotype='mp4')

~/anaconda3/lib/python3.7/site-packages/deeplabcut/pose_estimation_3d/triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
     95     if isinstance(video_path, str)==True:
     96         flag=True
---> 97         video_list = auxiliaryfunctions_3d.get_camerawise_videos(video_path,cam_names,videotype=videotype)
     98     else:
     99         video_list = video_path

~/anaconda3/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions_3d.py in get_camerawise_videos(path, cam_names, videotype)
    131                     putativecam2name=os.path.join(path,pref+cam_names[1]+suf+ending)
    132             #print([os.path.join(path,pref+cam+suf+ending),putativecam2name])
--> 133             if os.path.isfile(putativecam2name):
    134                 #found a pair!!!
    135                 video_list.append([os.path.join(path,pref+cam+suf+ending),putativecam2name])

UnboundLocalError: local variable 'putativecam2name' referenced before assignment

```
**How to Reproduce the problem**
1.I have named my video files as camera-1 and camera-2. They are named the same in the config.yaml file of the 2D and 3D projects
2. Both 2D projects (one for camera-1 and the other for camera-2) have the same body parts and skeletons. These were copied and pasted into the 3D project config.yaml file.
3. the scorer 3D name was set to "DLC_3D" in the 3D config.yaml
4. Snapshots to use in the config.yaml files is set to -1
5. I now pass the config_path3d and the video_path (which is a path to a new folder where all the videos from two cameras are copied). 
6. The triangulation step (seen below) leads to the mentioned error (also see screenshot attached)

video_path = '/home/dlc/Desktop/DeepLabCut-master/examples/videos-raw/'

deeplabcut.triangulate('/home/dlc/Desktop/DeepLabCut-master/examples/testing2-Paula-2020-03-20-3d/config.yaml',video_path, videotype='mp4')

**Screenshots**
![Screenshot from 2020-03-24 13-46-27](https://user-images.githubusercontent.com/56651907/77427037-ed01c800-6dd5-11ea-834e-b8562e1c800e.png)

**Additional context**
I am a beginner programmer. Thank you for your time!

**Comment by MMathisLab** [comment]
``Strange naming convention on your part. Respect.`` <-- at least you found an egg in the code ;) 

So, it means your videos are not named such that they can be paired. They must 

(1) start with whatever you named the cameras in the config.yaml:

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/Overviewof3D.md#4-triangulation----take-your-2d-to-3d

![image](https://user-images.githubusercontent.com/28102185/77474882-42e26a00-6dee-11ea-8244-dc913ad04d12.png)



(2) be "pair-able" 

i.e. cam1_myVideo12345 and cam_2myVideo12345 <- the endings need to be the same, otherwise the code cannot know which videos to "pair"

**Comment by paulavillafulton** [comment]
Worked! Thank you!

**Comment by RaulCastillo91** [comment]
Hello Paulina my name is Raul, the reason because i write you is because i am working with deeplabcut , and i have a few problems (very similar that yours), so i wonder if you can help me, i mean, it is possible that could you share share with me some videotutorial about, how you solved your problem of this topic
