### ISSUE TITLE
How can I label some body parts(key points) that are hidden?

### ISSUE THREAD

**Issue by ZZANZU** [DeepLabCut/DeepLabCut#651]
Hi, 
I was working on a project for making animal pose estimation model and I luckily found your project :)
It's super easy and well-documented. Really appreciate it!🙏🏻🙏🏻🙏🏻

Anyway, 
I followed some tutorials and ran some demo codes in [here](https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_yourowndata.ipynb).
In the progress of labeling from extracted frames, I was little confused by the way of labeling some key points that are hidden by other objects or body parts. 

Here's my question. **Do i have to annotate the key points even though the body parts are not shown? or just skip that part?**  

Thank you for your answer in advance. Have a good day😄

**Comment by AlexEMG** [comment]
It depends - if you want the model to guess the location of bodyparts (even if they are hidden), then you have to annotate them all. Otherwise, you do not.

**However, importantly you have to be consistent**. Whatever you did for labeling, you should also do for refinement.

I suppose, given how you asked, that you did not label hidden/occluded body parts during the labeling process. However, keep in mind that during the refinement step all bodyparts are shown. Check out "[Stage X and XI" in the protocols paper](https://www.nature.com/articles/s41596-019-0176-0) to see more details. 
I'm quoting for convenience:

"Based on the performance of DeepLabCut, four scenarios are possible:

- A visible body part with an accurate DeepLabCut prediction. These labels do not need any modification.
- A visible body part, but the wrong DeepLabCut prediction. Move the label’s location to the actual position of the body part.
- An invisible, **occluded body part.** Remove the predicted label by DeepLabCut with a right click. _Every predicted label is shown, even when DeepLabCut is uncertain. This is necessary, so that the user can potentially move the predicted label. However, to help the user to remove all invisible body parts, the low-likelihood predictions are shown as open circles (rather than disks)._
- Invalid image. in the unlikely event that there are any invalid images, the user should remove such images and their corresponding predictions, if any. Here, the GUI will prompt the user to remove an image identified as invalid."

(there is also a less up to date preprint: https://www.biorxiv.org/content/10.1101/476531v1)
