### ISSUE TITLE
Problem extracting frames

### ISSUE THREAD

**Issue by AlvaroTRB** [DeepLabCut/DeepLabCut#678]
macOS Catalina 10.15.4, with Anaconda Env, & DeepLabCut 2.x.

OS: iOS
DeepLabCut Version 2.1.7
Chrome

I´m trying to extract frames from a series of videos. When I try to extract them, the reading of the config.yalm gives me an error, saying that the video is corrupt. I can play those videos on my mac without problems. I´ve tried deactivating opencv and installing homebrew in my mac.

Screenshots

![image](https://user-images.githubusercontent.com/64780017/81316209-969dcf80-908b-11ea-83ac-8a13c2034b30.png)

Another person has tried the same process and made it without problem.

**Comment by MMathisLab** [comment]
instead of launching in your home directory, could you first cd to Desktop, i..e 
```
cd /Desktop
pythonw
import deeplabcut as dlc
dlc.create_new_project('EBO2', 'MUSNN', ['/videopath']) 
```
(perhaps the sym link doesn't have the correct permissions, or such). But, since it's not a code bug, I will close for now - but please report back when you get your video working. You could also use ffmpeg (which comes installed) to re-format the video if you continue to have issues).
