### ISSUE TITLE
unable to find a module

### ISSUE THREAD

**Issue by Catherine-YX** [DeepLabCut/DeepLabCut#721]
Hi,

I am running multi animal DeepLabCut v2.2.b5 on Google Colab.

The code I ran to train the network is

<deeplabcut.train_network('drive/My Drive/Colab Notebooks/data/dlc-ma-abc-2020-05-28/config.yaml',shuffle=5,trainingsetindex=0,gputouse=None,max_snapshots_to_keep=5, displayiters=1000,saveiters=20000,maxiters=100000)>

However, it gave an error message:

[ModuleNotFoundError: No module named 'deeplabcut.pose_estimation_tensorflow.dataset.pose_multianimal_imgaug']

I have checked the version of DeepLabCut installed using <deeplabcut.__version__>. It reported ['2.2b5']. Therefore I was using the right version.

I am wondering what I could do to fix this problem.

Thank you very much!

**Comment by MMathisLab** [comment]
looks like you are not using 2.2b5 then; if you just `pip install deeplabcut` because multi-animal is a beta release, and therefore could change, it does not install this version. I would recommend looking at this notebook. 

https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

also, this is too much training and will lead to poor results in 2.2b5; the max you should train for is 50,000 iterations. 

> deeplabcut.train_network('drive/My Drive/Colab Notebooks/data/dlc-ma-abc-2020-05-28/config.yaml',shuffle=5,trainingsetindex=0,gputouse=None,max_snapshots_to_keep=5, displayiters=1000,saveiters=20000,maxiters=100000)
