### ISSUE TITLE
[Potential Exception] Unexpected dimension reduction of parameter <scmap>

### ISSUE THREAD

**Issue by yzyw0702** [DeepLabCut/DeepLabCut#81]
**Describe the bug**
IndexError occur for scmap when it called function predict.argmax_pose_predic,
Locations:
> * line 115 in Evaluation-Tools/EvaluateNetworks.py
> * line 57 in Analysis-tools/AnalyzeVideos.py

**To Reproduce**
1. Generate a new labelled dataset with only one feature, e.g. [Finger1] in your given example.
2. train the res-network
3. run Step1EvaluateModelonDataset.py
4. You will see the error.
5. Reason is easy: scmap.dims should be 3 when training dataset includes more than 1 feature, but it will be decreased to 2 when with only 1 feature.

**Expected behavior**
For safety concerns, it is highly suggested to insert the following two lines into locations list at the very beginning of this description:
```python
if len(scmap.shape) == 2:
    scmap = np.expand_dims(scmap, axis=2)
```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04LTS
 - Anaconda Python3
 - CPU only

**Comment by AlexEMG** [comment]
Dear @yzyw0702 ,

I think this error might be based on an old version? - currently we have the following lines in predict.extract_cnn_output(outputs_np, cfg)

```
    if np.ndim(scmap)==2: # Case for only 1 body part!
        scmap=np.expand_dims(scmap,axis=2)
```
This will make the dimensions ny, nx, x 1 (if it is only 1 bodypart). Since both AnalyzeVideos and EvaluateNetworks use this predict.extract_cnn_output(outputs_np, cfg), the scoremap should have the right format for predict.argmax_pose_predict?

Does that make sense, or am I overlooking something?

Best,
Alexander

**Comment by yzyw0702** [comment]
Oh I see; it must be the problem of old version! Thanks ^_^
