### ISSUE TITLE
Train with multiple GPUs at once?

### ISSUE THREAD

**Issue by kebwi** [DeepLabCut/DeepLabCut#86]
I'm vaguely familiar with TF and have learned that while it can easily see the various GPUs on a system and select from them (and even be instructed which GPUs to see, as illustrated in the DLC examples) it can be a little trickier to get it to use multiple GPUs for a single job. I appears to involve adding a few lines of code here and there where TF is configured. Does DLC offer any simple hooks into multi-GPU training? If not, if I have overlooked straightforward configuration in this regard, then what would be involved in extended DLC to support this behavior?

Thanks.

**Comment by AlexEMG** [comment]
Dear @kebwi 

Unfortunately, we are not going to work on this but contributions are of course welcome.

The reason is that in a typical use case of DLC, one trains very rarely. I.e. annotate data train and then use this network for months on experimental data until there are some outliers, that then can be added to the training data. Thus one would only train every month or so. That said, you can also start from intermediate snapshots, so training can be as fast as 1h on a single NVIDIA GTX 1080Ti.

Perhaps you can describe your use case more, so I can understand why you are interested in improving training speed. 

We are, however, actively working on making inference faster and we will release an update for this next week. Stay tuned...



Alexander

**Comment by EmiliosIsaias** [comment]
Interesting idea!
Perhaps not for training, but for analysing multiple videos with multiple GPUs. I'm imagining a way to run `deeplabcut.analyze_videos( config_path, video_path, gputouse=[0, 1] )`, for example. Maybe this is already possible?
