### ISSUE TITLE
Refining labels and retraining network

### ISSUE THREAD

**Issue by eltabbal** [DeepLabCut/DeepLabCut#907]
This is a general question regarding the workflow after initial training, analyzing videos, extracting outlier frames, refining labels, merging training data, and creating a new training dataset. Once I reach this stage, I used to just retrain the network without changing its initial weights to the last snapshot from the previous iteration. For me, it is more logical to start from weights network has reached in the previous iteration. I do the following, I change the initial weight parameter in the /trian/pose_config.yaml to the last snapshot obtained from previous iteration and run the network. i have two questions 
1) Is that better than just training the network using initial weight from 0 
2) should i also change the initial weight parameter in /test/pose_config.

**Comment by jeylau** [comment]
Hello @eltabbal,
1. It is often better unless the outlier frames you extracted and corrected were due to poor labeling in the first place. In that case, it is better to retrain from scratch to avoid propagating those errors once more.
2. Changing the train/pose_cfg.yaml like you do is sufficient.

In the future, please prefer our [forum](https://forum.image.sc/tags/deeplabcut) for these questions and reserve GitHub for bugs or code-related issues; you will receive support from the entire community 😃
