### ISSUE TITLE
Unable to install MacOS gcc issue; (error: command 'gcc' failed)

### ISSUE THREAD

**Issue by McElligottLab** [DeepLabCut/DeepLabCut#962]
MacBook Pro with anaconda (python 3.8.3)

I have been unable to install DLC and am not sure if I can properly explain the problem I am having. Any help would be really appreciated! Heres what I’ve done so far: 
1. Installed anaconda
2. Verified that python is installed (python 3.8.3)
3. I have tried various ways (described in documentation) to create the DLC-CPU environment, and none of them have worked. In the past I was able to create an environment by opening the anaconda app, one of the tabs on the left says “environments”, then clicking “import” and selecting DLC-CPU.yaml from my desktop
This gives two errors:
a. "CondaEnvException: Pip failed”
b. “the “gcc” command requires the command line developer tools. Would you like to install the tools now?”
I follow the prompts to install but then receive the message “Can’t install the software because it is not currently available from the Software Update server.”

<img width="1085" alt="Screen Shot 2020-10-16 at 10 13 12 PM" src="https://user-images.githubusercontent.com/73007192/96326439-91f82280-0ffe-11eb-8444-0c0d73f54002.png">

**Comment by AlexEMG** [comment]
Related to: https://github.com/DeepLabCut/DeepLabCut/issues/830

**Comment by neurologic** [comment]
Hello,
I am trying to help a student install on their MacOS for help with labelling project videos and we ran into the same problem on Thursday. 
Conda creation of the DLC-CPU environment did not fatally fail, but deeplabcut was not installed at the end of environment creation (we can run again to show the terminal results). 
Then we tried manually installing deeplabcut==2.2b8 (we are doing multianimal) and that failed with the above gcc issue and developer tools install prompt (which did not go anywhere).
I will check what her OS specs are today, etc and add them here as soon as I have them.
It seemed like her error string included mentions of 'X-code' so I thought that having her install that would help. But Xcode seems like it takes up a lot of space on the computer (11GB) so it would be great if that were not the issue.

UPDATE:
This seems to be a macOS issue, not a DLC package issue (but let me know if y'all find otherwise).
After some troubleshooting it seems that this is an issue with a MacOS update to Catalina 10.15. 
Running the code ```xcode-select --install ``` seems to be the suggested fix (to get command line tools without installing full cumbersome X-code app) (https://www.datacamp.com/community/tutorials/homebrew-install-use). 
However, this does not work on the updated Catalina. Apparently the X-code command line tools were not included in the release of this OS version (https://developer.apple.com/forums/thread/659304).  
Does this all seem consistent with the error that you are encountering, @McElligottLab ?

If there is other information floating around or other fixes that you find, let me know.

**Comment by jeylau** [comment]
@McElligottLab, @neurologic, have a look at our troubleshooting section [https://github.com/DeepLabCut/DeepLabCut/wiki/Troubleshooting-Tips](url).
We had found the following fix to work (very much like the fix proposed above):

gcc: error: unable to find utility "gcc"
xcrun: error: invalid active developer path
These errors often occur after updating MacOS. The fix is to upgrade the Xcode toolkit as follows.
Open Terminal, and run xcode-select --install, followed by xcode-select --reset. Restart Terminal for changes to take effect. If the error persists, enter the command sudo xcode-select -switch /Library/Developer/CommandLineTools. Terminal will ask for your password; note that the password is not shown as you type.

**Comment by JunGitef17** [comment]
Thanks @jeylau ! I updated my High Sierra Mac OS to Big Sur recently and had the exact same problem of gcc suddenly becoming unavailable. Going through all your suggestions resolved it.
