### ISSUE TITLE
Backwards compatibility analyze_time_lapse_frames in maDLC 2.2 

### ISSUE THREAD

**Issue by felixhol** [DeepLabCut/DeepLabCut#995]
OS: Ubunu 18.04 and macOS
DLC: 2.2b8
conda env: dlc-cpu (on macOS) dlc-gpu (on ubuntu) cloned from repo

**Problem**
Upgrading from 2.0 (or 2.1) to DLC 2.2 breaks compatibility to analyze time lapse frames. The function ```analyze_time_lapse_frames``` is implemented for single animals in ```predict_videos.py``` but is missing int he multi-animal version ```predict_multianimal.py```. 

It would be wonderful if a workaround is available for this, or to know if this feature will be implemented again. 

**How to Reproduce the problem**
1. train maDLC
2. try to analyze image sequences using analyze_time_lapse_frames

**Comment by MMathisLab** [comment]
Hi @felixhol The time-lapse-frame was meant to be for sets of images that, as the name implies, can be taken min. or hours, apart, etc. Whereas in maDLC, we need time information for the tracking, so time-lapse won't work in this manner. If you feel you have data that is time lapse, but still enough temporal resolution to perform tracking, I would recommend simply making a video out of the individual frames. 

Otherwise, I don't think we want to support this; it could cause confusion that one could do time-lapse maDLC, which one cannot. If that makes sense!

**Comment by felixhol** [comment]
Hi @MMathisLab thanks for your reply (and of course for the amazing work!!!). Our time lapse acquisition ranges from 25 to 90 frames/second (25Hz is 3036 x 3036 pix, 90Hz  is 2048 x 2048 pix), so it's definitely at sufficient temporal resolution to do tracking. I  realized I can turn them into videos, but in certain contexts image stacks work quite well for us (with respect to specific cameras, and other analysis software that takes image sequences). A practical consideration is that we already have many terabytes of data in this format - I've been converting parts of the data pile using ffmpeg, but being able to run maDLC on image sequences would make things much easier. 
I realize that video is a much more common format for the majority of users, however, time lapse frames wouldn't necessarily be incompatible with maDLC tracking (though if I'm the only person interested in this, I completely understand it is not a priority).
thanks :)

**Comment by playaspec** [comment]
Rather than reencoding your images into a video format like h.264, you might consider a container format like mjpeg. It's little more than a wrapper around individual jpeg files concatenated into a stream. If you're already starting with jpegs to begin with, there should be no re encoding which can degrade the image. The other advantage is that they're easily indexed, meaning that you can trivially jump to or extract any frame or range of frames with little overhead. DLC accepts mjpeg by default. Conversely, it should be equally trivial to take a range of frames and containerize them into a .mjpeg file on the fly to feed to DLC provided you keep all the same encoding parameters as your source. Perhaps a simple preprocessor script as the first step of your analysis that containerises the sections you're analyzing would give you the features you seek.

ffmpeg is a great tool, but it's a bit unwieldy. You might get better mileage out of a bit of python automation that better models your particular analysis and data layout. Parsing a folder full of frames (or a subsection) and encoding them into mjpeg can be accomplished in about a dozen lines of python. Absent any re-encoding, it should take as much time as it takes to read the files, and write it back into the container. About the same time as copying them to a different drive. Hope this helps.

**Comment by felixhol** [comment]
thanks for the suggestion @playaspec - my files are tiff though, so I think this would result in a loss of image quality, or am I missing something? 
In addition to DLC based tracking, we also do other types of analyses that would be compromised by lossy compression.

**Comment by playaspec** [comment]
> my files are tiff though, so I think this would result in a loss of image quality, or am I missing something?

This really depends on the quality setting you choose to feed to the jpeg encoder. At 100%, loss is negligible if any. [Here's a really good discussion on the subject](https://photo.stackexchange.com/questions/30243/what-quality-to-choose-when-converting-to-jpg). Perhaps *jpeg isn't suitable for your use case, but it's worth evaluating. Being that jpeg is 24-bit, and your .tiff files may be 14-bit or better, there may be a loss of dynamic range, but you should be able to compensate for that with a little more preprocessing. 

> In addition to DLC based tracking, we also do other types of analyses that would be compromised by lossy compression.

By all means keep your source images as .tiff! Converting to jpeg/mjpeg isn't meant to be a substitute for your current raw storage, but a pathway for you to work with DLC.

**Comment by felixhol** [comment]
thanks for the advice and reference - I'll certainly give it a try!

**Comment by MMathisLab** [comment]
closed due to decision not to include for now!
